### ISSUE TITLE
Main Header Follow-Up: Use SVG instead of PNG

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#100]
# Issue

## ZenHub Issue

The home page is displaying an illustration in the right side, currently is a `assets/logo.png` image, however we need to use a SVG instead of a png file. The reason for this is because we want to display nice and crispy images in retina/large displays.

The scope of this task is about removing the png file and using an svg file instead.

**Comment by linux-nerd** [comment]
@crysfel I can take this up.
