### ISSUE TITLE
Main Header Follow-Up: Responsiveness

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#101]
# Issue

## ZenHub Issue

The current header in the home page is not responsive, in this task we need to set the width of the image on the left based on the parents width.

We are using flex to set the width of the parents, we need the SVG image to get the same width as the parent div and also to keep the ratio consistent, meaning the height should adjust based on the given width.

The scope of this task is only to adjust the width of the illustration.

Design for mobile: https://www.figma.com/file/MfEpHTzcJZTnclKSojQQdhpp/CodingCoach-Design-System?node-id=529%3A62

**Comment by crysfel** [comment]
@reeversedev done!

**Comment by tureey** [comment]
Well, I did the refactor of a different things on my PR before this new issues were created... sorry to don't say it before.

Fixed here https://github.com/Coding-Coach/coding-coach/pull/73
