### ISSUE TITLE
Main Header Follow-Up: Font Ratios seem a little off

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#103]
# Issue

## ZenHub Issue

The font ratios in the header are a little off, please follow the specs https://www.figma.com/file/MfEpHTzcJZTnclKSojQQdhpp/CodingCoach-Design-System?node-id=529%3A62

**Comment by tureey** [comment]
It's this still relevant? I mean, since mobile designs are done. Do we still have to change these font-sizes? @crysfel For me they look OK
