### ISSUE TITLE
Main Header Follow-Up: Hover styles for links and button

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#104]
# Issue

## ZenHub Issue

The `hover` styles for the button and links in the header section are missing. @emmawedekind will provide those styles soon.

Please work on this task until @emmawedekind provides the color/styles.

**Comment by nitish24p** [comment]
Can i pick this?

**Comment by emmawedekind** [comment]
Sure, assigned

**Comment by nitish24p** [comment]
Will use do this once the buttons PR gets merged :)

**Comment by crysfel** [comment]
The `Button` PR has been merged! When working on this task, make sure to use our shiny new `Button` :)

**Comment by crysfel** [comment]
Now we are using the `Button` component in the header, styles are now consistent
