### ISSUE TITLE
Main menu for mobile

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#105]
# Issue

## ZenHub Issue

In mobiles we need to show a hamburger menu at the top-left instead of displaying the main menu (for desktops/tablets).

When the user clicks the hamburger icon, the menu should slide in with a smooth animation. Internally it should have a close button, and three links: About, Mission, Contact.

Please follow the specs: https://www.figma.com/file/MfEpHTzcJZTnclKSojQQdhpp/CodingCoach-Design-System?node-id=529%3A62

**Comment by dhrubesh** [comment]
Hey, I will take this.
But just wanted to confirm if the `Button` component is ready or not? If not, I can work on it as well.

**Comment by crysfel** [comment]
I've assigned the button component to you: https://github.com/Coding-Coach/coding-coach/issues/112

**Comment by dhrubesh** [comment]
Sure Thanks! Can you assign this issue to me as well?

**Comment by tureey** [comment]
Since we will not do this I close the issue
