### ISSUE TITLE
Consistency in css class names

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#106]
# Issue

## ZenHub Issue

We have decided to use camel case for naming css classes, we currently have some sass files using snake case instead.

Please go through all css files and rename the classnames, for example `slack_org` to `slackOrg`. We want consistency in our codebase.

Don't forget to update the javascript files as well.

**Comment by linux-nerd** [comment]
I will take this up. I changed the classnames to snake case after a comment on my PR. I will revert snake case to camel case.

**Comment by crysfel** [comment]
Thanks, the PR has been merged!
