### ISSUE TITLE
Reusable Components: Button

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#112]
# Issue

## Description

We need to create a reusable `Button` component. We should also be able to define children with any content. The button should receive two properties, `onClick` and `theme`.

```
<Button onClick={onClick}>Test</Button>

<Button onClick={onClick} theme="primary">
  <Image src={image} />
  <span>Some Text</span>
</Button>
```

**Comment by nitish24p** [comment]
@dhrubesh can i pick this up im done with most of it need to create a PR? If thats okay

**Comment by dhrubesh** [comment]
Sure, please go ahead.

**Comment by emmawedekind** [comment]
Please update the pipeline to In Progress when you begin working.

**Comment by nitish24p** [comment]
@crysfel 
Instead should we have a generic button component which does
```javascript
const Button = ({children, ...rest}) => {
  const classes = classNames(
    styles.button,
   // other styles based on props
  )
  return (
    <button {...rest} className={classes}>
      {children}
    </button>

  )
};
```
This way we neednt have a label prop, the children can be text, image, span, loader whatever? what say?

**Comment by linux-nerd** [comment]
And instead of onPress I would suggest onClick event. This is a more generic event. This is helpful whenever we have to use cloneElement to clone some component/node `React.cloneElement(component, { onClick: this.handleClick })` we can use generic onClick instead of onPress as it will work for both `<Button />` and `<button></button>`

Something like this - 
```
<Button onClick={onPress} label="Ok" classes={classes} icon={<FontAwesomeIcon />} theme="primary" />

```

**Comment by crysfel** [comment]
@linux-nerd I'm ok with `onClick`, I was thinking since we are doing mobile first onPress/onTouch might make more sense.

Let's go with `onClick`, I will update the issue.

**Comment by crysfel** [comment]
@nitish24p that's what I was thinking for the second use case. I was just thinking on providing two different options, but it might makes more sense to have a single use case to avoid confusion.
