### ISSUE TITLE
Terms & Conditions

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#116]
## Description

Terms & Conditions MUST be created.  I can create a mock-up but we cannot deliver the landing page otherwise.

## Assets
The document can be found [here](https://docs.google.com/document/d/1_blcaj76xQ6swqhcCTuxnvwp1RjLyXv2j8bT-rB4qbU/edit?usp=sharing).

## Design
![image](https://user-images.githubusercontent.com/7671983/46428158-8ac98900-c743-11e8-8516-ca23449b0937.png)

**Comment by Venablena** [comment]
@linux-nerd Since this uses the same modal as Privacy Policy and Cookies, the same modal should be used for all of them and just change the text.

**Comment by CoryKelly** [comment]
Has this issue been taken yet?

**Comment by emmawedekind** [comment]
I don't think so? I can assign you @CoryKelly

**Comment by linux-nerd** [comment]
@CoryKelly If you have not started working on this, I can complete the same on my PR #117
