### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#117]
## Description

Privacy Policy MUST be created.  I can create a mock-up but we cannot deliver the landing page otherwise.

## Assets
[Here is a link](https://docs.google.com/document/d/19aG24XBouXTlRFnR37NHDIq2z7qCcFYMyVSQxmTz5dE/edit?usp=sharing) to the Google Doc with the Privacy Policy document.

## Design
![image](https://user-images.githubusercontent.com/7671983/46428177-987f0e80-c743-11e8-8e36-29f87b956771.png)

**Comment by linux-nerd** [comment]
I can take this up :)

**Comment by emmawedekind** [comment]
Super!

**Comment by emmawedekind** [comment]
Please create this dialog so it's extensible for Terms & Conditions as well as Cookies.

**Comment by crysfel** [comment]
I think we should break this task into thee more:

1.- We need a reusable `Button` component (We have a task for this: https://github.com/Coding-Coach/coding-coach/issues/112)
2.- A reusable `Panel` component with Title, Content and footer
3.- A reusable `TextField` component with `multiline` property to render a textarea.

Then we could create a `LegalDialog` component that looks exactly like this:

```
<LegalDialog title="Terms & Conditions" content="This terms and conditions...." onClose={doSomething}  />

<LegalDialog title="Private Policy" content="We the people..." onClose={doSomething}  />
```

**Comment by linux-nerd** [comment]
@crysfel , @emmawedekind I am working on this. One question - When should this popup open? Open the click of ?

**Comment by tureey** [comment]
In the footer there is a `footer-privacy` link. I guess that clicking there. @linux-nerd

**Comment by crysfel** [comment]
@linux-nerd what @tureey said 👆
