### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#120]
## Description

- [x] Add "Cookies" to the footer (Design 2).  When clicked, this should open a modal (Design 3).

- [x] Add the cookie banner fixed on scroll (Design 1)

## Assets
The text can be found [here](https://docs.google.com/document/d/1Bmo9ZWiHNSjJ5ccsKEfiSTpqtC-KIP91IXQiwnsx5m0/edit?usp=sharing).

### Design 1
![image](https://user-images.githubusercontent.com/7671983/46427359-8f8d3d80-c741-11e8-8b8c-f9bb25533cb8.png)

### Design 2
![image](https://user-images.githubusercontent.com/7671983/46427312-68367080-c741-11e8-95fd-97c1e0d60679.png)

### Design 3
![image](https://user-images.githubusercontent.com/7671983/46428205-a765c100-c743-11e8-8358-9a65f2b428e3.png)

**Comment by Venablena** [comment]
Happy to do this -but is someone already working on the footer/has it been added to a pending pull request, I don't see it in the repo?

**Comment by Venablena** [comment]
@linux-nerd If you're creating the modal, the same should be used for this. I can do the designs 1 and 2.

**Comment by emmawedekind** [comment]
Footer task is here: https://github.com/Coding-Coach/coding-coach/issues/122

**Comment by Venablena** [comment]
What's the expected behavior here? Should the overlay be shown every time the page is loaded or do we want to keep something in local storage, for example, to remember who has visited the page already? I don't know what the rules here are at all.

**Comment by emmawedekind** [comment]
The cookies banner should appear at the bottom of the screen (sticky). The modal only appears if they click the link in the footer.

**Comment by emmawedekind** [comment]
I've posted this on Invision. Please see the links in the Slack channel.

**Comment by Venablena** [comment]
@emmawedekind I didn't see this in InVision but the above image is enough, I think :).
@crysfel Do you want to store it in localStorage without expiration (when the icon has been clicked once on any given device/profile, we won't show this again) or use sessionStorage (it will pop up every time a new window is opened)? I think the latter sounds annoying but just want to make sure. Is it enough to just save something noting that the icon has been clicked (getting the user's IP address would require an external library, I believe)?

**Comment by crysfel** [comment]
I'd say to save in the local storage to show it only once. A boolean value is ok to save, `acceptedCookies=true`.

**Comment by tureey** [comment]
`AreCookiesAccepted`? 😋
