### ISSUE TITLE
Create Email Mailing List & Send First Email

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#121]
## Create Email Design
Create a welcome email to all of the survey participants. This will ensure retention.

**Comment by emmawedekind** [comment]
Yes that would be great!!

**Comment by emmawedekind** [comment]
Please accept the organization invitation!

**Comment by crysfel** [comment]
Assigned to @dbanbahji

**Comment by dbanbahji** [comment]
Awesome thanks, already started.

**Comment by tureey** [comment]
I set the task in progress

**Comment by mayeedwin** [comment]
We can use Firebase Authentication service and store the emails with cloud Firestore and even send the needed sign up email.

**Comment by emmawedekind** [comment]
Do you guys want a design for an email template?

**Comment by tureey** [comment]
Just sketch something fast. If not, we can use a standard template... there are a lot!
If not, select like 2-3 templates, customize them with the logo and do a poll in slack, as you prefer!

I would go for something minimal though! @emmawedekind

**Comment by dbanbahji** [comment]
Yeah i started on some of the html email part and some trying to keep it mobile responsive, but its just really general text. Do we have a logo or pictures or a message we want to really convey?

**Comment by tureey** [comment]
@dbanbahji FYI, @emmawedekind payed for a logo and something else.
I don't know how much time will take but, I would use a placeholder and use the Logo once we have it.

Related to the texts and copies, we should think about what kind of platform do you want. Neutral or close to the user? 

For a welcome email though, I would do something like
```
Welcome userName,

First of all thank you for join our awesome community! We hope you find the mentor or the people to teach that you are willing to meet.


// we could provide some links here like, dashboard, your profile etc..

Bests,
Your new home.
```

**Comment by tureey** [comment]
I do thing the easiest and most beautiful are the ones with minimal design. A logo, some text customized using the userName, some information and links to help him out reaching interest points for new users and ofcourse, a warm welcome to the community/family!

You are in cahrge @dbanbahji  hahahah :yum:

**Comment by emmawedekind** [comment]
I have set up a Mail Chimp account for us and sent the first campaign:
https://mailchi.mp/0f6dc50ad189/welcome-to-coding-coach
