### ISSUE TITLE
Add links for social media accounts

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#124]
Adding links to social media icons.
Facebook: https://www.facebook.com/codingcoachio/
Twitter: https://twitter.com/codingcoach_io
Instagram: https://www.instagram.com/codingcoach_io/

**Comment by nero2009** [comment]
Hi Emma, is this task taken

**Comment by emmawedekind** [comment]
Nope, I can assign you if you're interested!

**Comment by emmawedekind** [comment]
Closing as this has already been implemented.
