### ISSUE TITLE
Reusable Components: TextField

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#125]
# Issue
We need to create a `TextField` component to use in different parts of our application. The component should be reusable and allow us to customize styles easily.

```
const classes = {
  root: styles.someCustomClassForTheRootElement,
  input: styles.customCssForTheInput,
  label: 'something-here',
};

<TextField value={value} onChange={onChange} classes={classes} label="Email" multiline={true|false} />
```

## Properties
- **value** The text to display in the textfield
- **onChange** A function that receives the new value when a user types a new char
- **onFocus** A function that gets executed on focus
- **onBlur** A function that gets executed on blur
- **classes** An object containing custom css classes to apply to the component
- **label** A string with the label for this textfield
- **multiline** if true renders a `textarea`, defaults to `false`

**Comment by dhrubesh** [comment]
If this one's unassigned, I would like to take this up.

**Comment by sojelee** [comment]
I am taking this issue

**Comment by crysfel** [comment]
I'm taking this, we need this component in order to work on the auth forms

**Comment by sojelee** [comment]
Thanks @crysfel go ahead
