### ISSUE TITLE
Reusable Components: Panel

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#127]
# Description
We need a `Panel` component that we can use anywhere in our application. It should be able to accept  a title, content and components in the footer.

```
const classes = {
  root: styles.classNameForRootElement,
  title: styles.classForTheTitle,
  close: styles.classForTheCloseButton,
  body: styles.classForTheBodyContainer,
  footer: 'custom-class-for-the-footer-container',
};

<Panel closable={false} onClose={onClose} classes={classes} modal={true}>
  <Panel.Header>Some title here</Panel.Header>
  <Panel.Content>
    <img src="something.png" />
    <div>
       <p>We should be able to add anything as the content<.p>
    </div>
  </Panel.Content>
  <Panel.Footer>
    <CustomFooterComponent />
  </Panel.Footer>
</Panel>
``` 

If the `modal` property is set to `false`, the panel should render in place. For example in a sidebar or anywhere else.

## Properties
- **title** A string with for the main title (Optional)
- **closable** If `true` the panel should display a close icon at the top, defaults to `false` (Optional)
- **onClose** A callback when use clicks the close icon (Optional)
- **modal** If `true` it shows the panel like a modal window, defaults to `false`
- **classes** An object with custom classes to apply to the inner elements of the panel (Optional)

## Design
![image](https://user-images.githubusercontent.com/7671983/46428177-987f0e80-c743-11e8-8e36-29f87b956771.png)

**The `Panel` component should only need the `title` and `background` styles from the design**, The content will be provided by others.

**Comment by linux-nerd** [comment]
@crysfel I was thinking of something like this - 
```
const classes = {
  root: styles.classNameForRootElement,
  title: styles.classForTheTitle,
  close: styles.classForTheCloseButton,
  body: styles.classForTheBodyContainer,
  footer: 'custom-class-for-the-footer-container',
};

<Panel trigger={<Button>Open Me</Button>} closable={false} onClose={onClose} classes={classes}>
  <Panel.Header>Some title here</Panel.Header>
  <Panel.Content>
    <img src="something.png" />
    <div>
       <p>We should be able to add anything as the content<.p>
    </div>
  </Panel.Content>
  <Panel.Footer>
    <CustomFooterComponent />
  </Panel.Footer>
</Panel>
```

The trigger will mount the component passed to it and on click of that component the popup will be toggled. Although for this structure 3 extra components will be created but it looks neat. Any thoughts?

**Comment by crysfel** [comment]
I don't think the `trigger` property is necessary. Also, we might want to use this panel without the modal window functionality, just a regular panel container in the sidebar for example. Therefore, I think we should add a `modal` property for the case when we want to show the panel as a modal window.

```
<Panel closable={false} onClose={onClose} classes={classes} modal={true}>
  <Panel.Header>Some title here</Panel.Header>
  <Panel.Content>
    <img src="something.png" />
    <div>
       <p>We should be able to add anything as the content<.p>
    </div>
  </Panel.Content>
  <Panel.Footer>
    <CustomFooterComponent />
  </Panel.Footer>
</Panel>
```

I'm going to update the original issue with these changes.

**Comment by arthurbuhl** [comment]
Just wanted to know, in case the image inside this panel is of very large size, will that prevent the whole panel from rendering until the image is loaded fully?

**Comment by crysfel** [comment]
@arthurbuhl which image?

**Comment by arthurbuhl** [comment]
The image inside the sample panel markup inside `Panel.Content` below

```jsx
<Panel closable={false} onClose={onClose} classes={classes} modal={true}>
  <Panel.Header>Some title here</Panel.Header>
  <Panel.Content>
    <img src="something.png" />   /* <<------ This image here */
    <div>
       <p>We should be able to add anything as the content</p>
    </div>
  </Panel.Content>
  <Panel.Footer>
    <CustomFooterComponent />
  </Panel.Footer>
</Panel>
```

**Comment by crysfel** [comment]
No, the content should be independent of the Panel. We are going to add a placeholder for loading large images, I have a PR where I'm going to include that.

**Comment by tureey** [comment]
Am I the only one that doesn't like the name `closable`? What about `canBeClosed`?

**Comment by linux-nerd** [comment]
> Am I the only one that doesn't like the name `closable`? What about `canBeClosed`?

I am fine with closable. :)

**Comment by linux-nerd** [comment]
> I think closable is okay. It's succinct.

I like that word `succinct`

**Comment by crysfel** [comment]
First time I hear the word `succinct` 👌

**Comment by tureey** [comment]
Same hahaha I had to translate that. Worst part? I had to look for the meaning of the Spanish word too hahaha 🤦‍♂️

**Comment by linux-nerd** [comment]
Haha I mostly come across this word in the blog posts and all the time I skipped by inferring the meaning. When @emmawedekind used it I searched how to pronounce it 😂

**Comment by crysfel** [comment]
Great work!
