### ISSUE TITLE
'Coding Coach' text is coming in a single line.

### ISSUE THREAD

**Issue by linux-nerd** [Coding-Coach/coding-coach#128]
# Issue

## Description

PR #73 overwritten PR #99 changes done to h1 tag to split the content to multi line. Right now the text 'Coding Coach' is coming in a single line.
Is this the required behaviour?

**Comment by tureey** [comment]
Yes! I am using <br> to force the text be in 2 lines. But... I changes in another PR to use \n so it is isomorphic

**Comment by linux-nerd** [comment]
@tureey I saw that '\n' for the line break. But its not working (not breaking the word in multiple lines) on Chrome version 69.0.3497.100 (Official Build) (64-bit) and Firefox Quantum version 62.0.3 (64-bit) on Mac

**Comment by tureey** [comment]
Mhh shit. I did not now that.. I didn't want to use `<br/>`...

**Comment by linux-nerd** [comment]
PR #113 fixed that issue using css. I was wondering if we decided against that technique, as it was merged by @crysfel 2 days back.
If there was no discussion and if you are fine with it, I can make changes and raise a new PR for the same.

**Comment by crysfel** [comment]
@linux-nerd please do that, I liked your original implementation

**Comment by emmawedekind** [comment]
Assigned
