### ISSUE TITLE
As user I want to be able to scroll to the top clicking a button once I am not on the top of the page

### ISSUE THREAD

**Issue by tureey** [Coding-Coach/coding-coach#130]
# Issue
Once the user has scrolled down, he can't go to the top of the page. He has to scroll to the top manually.

Would be nice to have a button that scrolls-top.

## Description

Float button at the bottom-right corner of the screen that scrolls to the top of the page

## Direct Requirements

- [ ] Create the component
- [ ] Functionality to scroll top

**Comment by tureey** [comment]
I was going to do that but since I still have to finish https://github.com/Coding-Coach/coding-coach/pull/123 I assign this to you

**Comment by tureey** [comment]
@emmawedekind @crysfel I can't assign the task to him. Any reason why he doesn't appear on the list?

**Comment by emmawedekind** [comment]
I sent him an invitation to the org. He has to accept.

**Comment by crysfel** [comment]
@dbanbahji done!

**Comment by dbanbahji** [comment]
Thanks!

**Comment by emmawedekind** [comment]
What's the status of this?

**Comment by tureey** [comment]
@dbanbahji ping

**Comment by kriyeng** [comment]
Would you like to apply the scroll button finally? I can offer to solve this issue if there're no news.

**Comment by crysfel** [comment]
@kriyeng all yours!! Thanks!!
