### ISSUE TITLE
Integrate `bundlesize`

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#133]
# Issue

We need to integrate the `bundlesize` package: https://github.com/siddharthkp/bundlesize It will help us to keep track of our final bundle.

**Comment by dhrubesh** [comment]
Hey, I will take this.

**Comment by emmawedekind** [comment]
Assigned!

**Comment by moshfeu** [comment]
What's the status?

**Comment by palashmon** [comment]
Any updates on this?

We need to do a few more things here:

1. Add it to our scripts in `package.json` like:

	```json
	"scripts": {
  	  "test": "bundlesize"
	}
	```

2. Add the `path` and `maxSize` in our `package.json`:

	```json
	{
	  "name": "your cool library",
	  "version": "1.1.2",
	  "bundlesize": [
	    {
	      "path": "./dist.js",
	      "maxSize": "3 kB"
	    }
	  ]
	}
	```

2. [Authorize bundlesize for status access](https://github.com/siddharthkp/bundlesize#2-build-status), copy the token provided.

3. Add this token as `BUNDLESIZE_GITHUB_TOKEN` as an environment parameter in your CIs project settings. This has to be done by someone with full access to CI.
