### ISSUE TITLE
Integrating Flow

### ISSUE THREAD

**Issue by arthurbuhl** [Coding-Coach/coding-coach#144]
### Description

[Flow](https://flow.org/en/) is a static type checker for your JavaScript code. It does a lot of work to make us more productive. Making us code faster, smarter, more confidently, and to a bigger scale.

Create React App already supports Flow by default. All we need to do is install Flow and create a `.flowconfig` file by running `flow init`.

```sh
yarn add --dev flow-bin
yarn run flow init
```

Flow will be run as part of create-react-app's scripts.

Also, Flow and Babel are designed to work great together. It takes just a few steps to set them up together.

```sh
yarn add --dev babel-preset-flow
# or
npm install --save-dev babel-preset-flow
```

Then add flow to your Babel presets config.

```json
{
  "presets": ["flow"]
}
```

**Comment by nitish24p** [comment]
If we do this then proptypes arent needed right

**Comment by charlesjliu** [comment]
I don't think we wanted to introduce type checking to keep the barrier to entry for other contributors low.

That said, if we do want to add type checking ... `typescript` >>> `flow` all day 🙃

**Comment by tureey** [comment]
I agree with @charlesjliu

**Comment by crysfel** [comment]
> I don't think we wanted to introduce type checking to keep the barrier to entry for other contributors low.

This is the reason we decided not to use flow or typescript

**Comment by tureey** [comment]
So the conversation is over. Isn't it? If so, then the issue should be closed @crysfel

**Comment by arthurbuhl** [comment]
Ok, seems like we don't need flow here. Should I close this issue @emmawedekind @crysfel?

**Comment by emmawedekind** [comment]
I can go ahead and do it, thanks.
