### ISSUE TITLE
Add rel="noopener noreferrer" to target="_blank"

### ISSUE THREAD

**Issue by arthurbuhl** [Coding-Coach/coding-coach#163]
### Description

`rel="noopener noreferrer"` should be added to links containing `target="_blank"` as a precaution against reverse tabnabbing. For more information, please refer to the following article:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

### Code

https://github.com/Coding-Coach/coding-coach/blob/028e2d01a74712d6745671d00b13159ff5459f62/src/components/contact/Contact.js#L14

**Comment by tureey** [comment]
I'll take this

**Comment by palashmon** [comment]
This issue can be closed now.

**Tip:** You can include keywords in your pull request descriptions, as well as commit messages, to automatically close issues in GitHub when a corresponding pull request is merged.

More Info here: [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by tureey** [comment]
I did not now that @palashmon. That's ammazing!

**Comment by DanielRuf** [comment]
`closes #issuenumber` in commits and PRs works. or `fixes #issuenumber`

**Comment by tureey** [comment]
but doesn't matter which commit? I mean, can I just do it in the first one?  @DanielRuf

**Comment by tureey** [comment]
nice! Thank you so much @DanielRuf

**Comment by tureey** [comment]
Finished and merged.
