### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#165]
![pp1](https://user-images.githubusercontent.com/7671983/47450785-69017600-d7c6-11e8-8b07-34ee03525934.png)

**Comment by crysfel** [comment]
@gulshansainis done! @emmawedekind are you going to upload the icon here: https://projects.invisionapp.com/boards/UF3Q7E6QEZM ??

**Comment by emmawedekind** [comment]
Here is the link to the favicon: https://projects.invisionapp.com/d/main#/projects/boards/6261486/186092339

**Comment by emmawedekind** [comment]
I don't know why you wouldn't have access... can you please reach out to me on Slack?
