### ISSUE TITLE
Add Mail Chimp email section

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#169]
Add a section to the new landing page which allows users to sign up for the Email list through Mail Chimp. Design to follow.

<img width="1531" alt="screen shot 2018-11-07 at 11 08 15 am" src="https://user-images.githubusercontent.com/219207/48147674-7d8d4600-e27d-11e8-8964-10e0f3c1f26f.png">

Link to sketch file:
https://sketch.cloud/s/xVR5A/wL9QEbE

**Comment by crysfel** [comment]
I'm taking this!

**Comment by emmawedekind** [comment]
I believe we're replacing this with the pop-up Mail Chimp modal! #269
