### ISSUE TITLE
Async legal content

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#174]
# Issue

## Description

We currently have the *privacy policy* and  *terms and conditions* content inside the i18n files. One of the problems that we have is that these documents contain some styles and custom content. For now we are releasing it as it is.

Given that modal won't be open very frequently by the users, it would be better to store the content of these documents in markdown files and dynamically load them on demand.

As a result, we can easily update the content without the need to update the source code, all we will do is to update those external files and done! It will be easier to manage, also... if at some point we need to send them to an attorney it will be super simple for them to take a look.

**Comment by tureey** [comment]
For sure that there are libraries that convert from `markdown` to `jsx`. At the company I work for we have one but it's private.

I'll try to look for it and update the description

**Comment by ajrussellaudio** [comment]
I'd like to take this on, using [remark](https://github.com/remarkjs/remark) and [remark-react](https://github.com/mapbox/remark-react) to solve the problem. It would be a learning exercise for me, as I don't know these libraries well, but they're used by Next.js and Gatsby, and I'd like to dig into them.

**Comment by crysfel** [comment]
That was quick! Thanks for contributing! Please join our [slack dev channel](https://join.slack.com/t/coding-coach/shared_invite/enQtNDY3NjI0NzYwNTEyLTA1OTNhZmI0MWNjZTdhMTdiNDc0YjZjYTg3NWU5YmU2MjVjMWUwMWQ3ZWU2Y2I5YjM1YjAyZTkzNWU3YjczOTQ) and ask @emmawedekind to add you to the github organization.
