### ISSUE TITLE
Replace bear icon with logo

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#176]
![image](https://user-images.githubusercontent.com/7671983/47600336-05db3380-d9c0-11e8-864f-3b925696c2a0.png)

You can find the logo here:
https://projects.invisionapp.com/boards/UF3Q7E6QEZM/

![image](https://user-images.githubusercontent.com/7671983/47600351-38852c00-d9c0-11e8-87a7-1e04f0a4b59f.png)

**Comment by splinterific** [comment]
Happy to give it a look if you're ok with that! :)

**Comment by splinterific** [comment]
I left the old hero logo in the assets folder. I can update and remove if needed. I also updated the alt text

**Comment by emmawedekind** [comment]
Closed with #177
