### ISSUE TITLE
Fix height of Privacy Policy modal

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#186]
Privacy policy modal has whitespace.  It should be fit to the content size.

![image](https://user-images.githubusercontent.com/7671983/47732212-072d8a00-dc66-11e8-801d-e9b27e42f89d.png)

**Comment by feysalikbal** [comment]
I can have a look at it.

**Comment by emmawedekind** [comment]
Are you added to the org? I can't assign you.

**Comment by feysalikbal** [comment]
No, I am not added to the organization.

**Comment by feysalikbal** [comment]
Mobile:
![privacy_policy_modal_res_320](https://user-images.githubusercontent.com/21144691/47946351-649a3300-df13-11e8-9da7-419fb2675ef8.jpg)

Tablet:
![privacy_policy_modal_res_768](https://user-images.githubusercontent.com/21144691/47946362-7f6ca780-df13-11e8-93a0-47550d1c5d2f.jpg)

Desktop:
![privacy_policy_modal_res_1024](https://user-images.githubusercontent.com/21144691/47946366-85fb1f00-df13-11e8-90a3-1f0bad93d3a7.jpg)

**Comment by tureey** [comment]
Looks really good! @feysalikbal

**Comment by feysalikbal** [comment]
Thanks :)

**Comment by emmawedekind** [comment]
Any update on this? @crysfel are we good to merge?

**Comment by crysfel** [comment]
@emmawedekind the current PR is not adding styles for mobile, given that this issue is very old and we haven't head back from @feysalikbal... we should close the PR and open this issue for someone else who wants to take it.

**Comment by kriyeng** [comment]
It would be great if I could fix this issue. How could I be added to the org?

Here're the snapshots

Desktop
![modal1](https://user-images.githubusercontent.com/3359663/51412372-aa0dea00-1b6b-11e9-8fe6-03bbcfc140c6.PNG)

Mobile
![modal2](https://user-images.githubusercontent.com/3359663/51412373-aa0dea00-1b6b-11e9-9824-7be640291ebe.PNG)

Mobile landscape
![modal3](https://user-images.githubusercontent.com/3359663/51412370-a9755380-1b6b-11e9-8fe5-41862b121722.PNG)

Thank you!

**Comment by kriyeng** [comment]
Sorry, this fixes when content is short, but when it's larger (on bigger resolutions), the modal get out of the screen. You can scroll, but the whole modal, not just the content part. I could look for a solution if you assign me the issue.

**Comment by emmawedekind** [comment]
Hey @kriyeng still interested?

**Comment by emmawedekind** [comment]
I've added you to the organization so if you want this issue, I can assign it to you!

**Comment by kriyeng** [comment]
Great, thank you @emmawedekind. Yes, I'd like to try.

**Comment by emmawedekind** [comment]
Great, you're assigned @kriyeng
