### ISSUE TITLE
The user is taken to different sections without animation.

### ISSUE THREAD

**Issue by linux-nerd** [Coding-Coach/coding-coach#195]
# Issue

## Description

When Learn More is clicked, it animates and take the user to About Section. But when the user navigates from the header links -> About/Mission/Contact. The user is taken to these sections without animation.

The behaviour should be consistent.

## Direct Requirements

- on click of the menu items, the user should be taken to the desired section with animation.

**Comment by tureey** [comment]
The call the action (button) takes you smoothly to the about sextion because it uses a scrollIntoView. The click event is catched and then we scroll.

Same logic would have to be implemented.

**Comment by tureey** [comment]
Shit sorry hahahah

**Comment by linux-nerd** [comment]
> Shit sorry hahahah

😆

**Comment by linux-nerd** [comment]
PR - #201 raised

**Comment by crysfel** [comment]
Thanks!
