### ISSUE TITLE
Modal when opened changes the url

### ISSUE THREAD

**Issue by linux-nerd** [Coding-Coach/coding-coach#197]
# Issue

## Description

Whenever a modal window is opened, the url gets appended with `#something`. In case of popup this dosen't make sense.

## Screenshot

<img width="1511" alt="screen shot 2018-10-31 at 9 26 35 am" src="https://user-images.githubusercontent.com/2995641/47765398-c5e1bc80-dcef-11e8-81ab-9177db81b6ec.png">

<img width="1532" alt="screen shot 2018-10-31 at 9 26 06 pm" src="https://user-images.githubusercontent.com/2995641/47801345-0541f480-dd54-11e8-93af-58177f475ad3.png">

## Steps to Reproduce

1. Click on Cookies Policy
2. Observe the url

## Direct Requirements

- Do not update the url
- Please apply same fix to Privacy Policy, Terms and Condition and Cookie Policy in the footer

**Comment by tureey** [comment]
To do this then the footer links should be buttons and not links if I am not wrong. It actually makes more sense since they are not acting as anchors

**Comment by linux-nerd** [comment]
> To do this then the footer links should be buttons and not links if I am not wrong. It actually makes more sense since they are not acting as anchors

Yep 👍

**Comment by nero2009** [comment]
Can I handle this or is someone already on it

**Comment by linux-nerd** [comment]
@nero2009 Go ahead!
@emmawedekind can you assign this issue to @nero2009

**Comment by nero2009** [comment]
Should I use the Button component or I should use a html button then style it like a link

**Comment by linux-nerd** [comment]
I would recommend using Button component. @crysfel @tureey your view?

**Comment by nero2009** [comment]
The Button component looks good
![cookies](https://user-images.githubusercontent.com/29065069/47786907-904bcc00-dd0d-11e8-8360-642b26791dfd.JPG)

**Comment by emmawedekind** [comment]
No this needs to be a ternary button, which looks like a link.

**Comment by emmawedekind** [comment]
Do not use a primary button for this, please.

**Comment by nero2009** [comment]
Oh my bad, I didn't know there was a tertiary button that will be a better fit.
![cook](https://user-images.githubusercontent.com/29065069/47790193-d194a980-dd16-11e8-886f-187f0d7cd3c6.JPG)

**Comment by linux-nerd** [comment]
@nero2009 Please apply same fix to Privacy Policy, Terms and Condition and Cookie Policy in the footer. I will update the issue 😄

**Comment by tureey** [comment]
As a work around is okay. I agree with @reactiongears though. But we need first to develop something form `markdown` to `jsx` and think about how to translate them!
