### ISSUE TITLE
Navbar spills over onto second line on narrowest screens

### ISSUE THREAD

**Issue by msweeneydev** [Coding-Coach/coding-coach#204]
# Issue

## Description

Navbar spills over onto second line on narrowest screens, this was first noticed using an iPhone SE and after investigating this issue seems to occur almost exactly at the 320px breakpoint.

## Screenshot

![alt text](https://image.ibb.co/dvQ2Sf/Screenshot-2018-10-31-22-16-05.png "Navbar issue")

## Direct Requirements

- [x] Add media query to handle display of Navbar on narrowest screens

**Comment by msweeneydev** [comment]
Plenty of ways this could be handled, the simplest being to take a bit of padding away, changing from 2rem to 1rem would achieve this but will look slightly odd with regular left alignment. I suggest reducing the padding at the <320px breakpoint but also using justify-content: space-between to keep things readable but aligned.

**Comment by tureey** [comment]
What device is this? IPhone5 has not a lot of width.. and it looks fine there!

I've check the styles and personally I would change the `margin-right` of the links from `2rem` to `1rem`, but the implementation is all your thing ^^

Surprise us @msweeneydev ! haha

**Comment by msweeneydev** [comment]
This is using an iPhone SE, I don't think you can get much narrower these days so it's only a minor issue.

I'll have a look over the weekend but I think I'll probably go with what I outlined above 👍

**Comment by tureey** [comment]
Good catch btw with the issue! And thanks for contributing 😄

**Comment by emmawedekind** [comment]
Thanks so much for opening an issue and contributing :)
