### ISSUE TITLE
Manifest.json needs completing

### ISSUE THREAD

**Issue by msweeneydev** [Coding-Coach/coding-coach#205]
# Issue

## Description

Currently, the manifest remains as the boilerplate. It needs a few minor changes to bring it it line but is certainly not urgent.

## Direct Requirements

The following need to be changed:

- [x] short_name
- [x] name
- [x] theme_color
- [x] background_color

## Indirect Requirements

We may wish to have some discussion about further additions to the manifest, there are plenty of good examples about to get some ideas. For anyone not familiar with its purpose, [this link](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json) should bring you up to speed 🙂

**Comment by crysfel** [comment]
Would you like to take this? 

For the current deployment I manually updated that file just before deploying https://github.com/Coding-Coach/coding-coach/blob/gh-pages/manifest.json#L2 😂

**Comment by msweeneydev** [comment]
Happy to take it, another I’ll get round to this weekend :thumbs_up:

**Comment by msweeneydev** [comment]
> Is it me or the short name is not short? @crysfel AHHAHAHAHAHAHAH 🤣

Both names can be the same actually, the only constraint on the short_name is that it must be 12 characters or less, lucky it's 12!
