### ISSUE TITLE
Fix unsafe state mutations

### ISSUE THREAD

**Issue by msweeneydev** [Coding-Coach/coding-coach#209]
# Issue

## Description

There are two points in the codebase where we are directly referencing the 'current' state inside of a setState call. Due to the way React can 'batch' setState calls for performance reasons, this is unsafe and can lead to unpredictable outcomes.

Here is how the functions are currently constructed:

`toggleModal = () => {
    this.setState({
      showModal: !this.state.showModal,
    });
  };`

Here is an example of how they should be constructed:

`  toggleModal = () => {
    this.setState(prevState => ({
      showModal: !prevState.showModal,
    }));
  };`

See [this link](https://reactjs.org/docs/react-component.html#setstate) for more details.

## Direct Requirements

- [ ] Fix in components/Modal
- [ ] Fix in pages/Home

**Comment by crysfel** [comment]
@tureey this is what I was referring in my code review, I thought we changed it. Anyway, there's a PR fixing this.

Thanks @msweeneydev for catching that!

**Comment by tureey** [comment]
oh, I did not understand you then @crysfel 🙏 

 I am used to deconstruct state `{ }`
