### ISSUE TITLE
Update button styles

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#212]
Primary and Secondary button hover/focus states need updating. I am removing the bottom border darkening and adding a full on background-shade.

Please add a transition of .1s linear on the background color so it flows smoothly.

Additionally, I've added styles for Primary and Secondary round buttons.  There are instances where we'll need round buttons so please add them to the component :)

![image](https://user-images.githubusercontent.com/7671983/48021874-f5eaee80-e139-11e8-89c0-b3eb1c1a1655.png)

**Comment by crysfel** [comment]
@splinterific all yours!

**Comment by crysfel** [comment]
@emmawedekind can you upload the sketch file to invision board? It will be easier to implement if we have it ;)

**Comment by emmawedekind** [comment]
You can grab it all here: https://sketch.cloud/s/xVR5A

**Comment by nitish24p** [comment]
@emmawedekind sorry but is there a difference between the hover and the clicked states.. both looked identical

**Comment by emmawedekind** [comment]
The other version of the buttons didn't highlight the entire button on hover/focus (didn't use bg-color). It just added a bottom border (inset) of sorts and it looked off so I changed it to be the entire bg-color change.

**Comment by splinterific** [comment]
there's already a `.pill` class that looks after the rounded variant so i've just added it to the scss config at `$border-radius-pill` and updated `button.scss`. PR on the way

**Comment by emmawedekind** [comment]
Wonderful you rock, thanks!
