### ISSUE TITLE
Automate deployment to gh pages

### ISSUE THREAD

**Issue by linux-nerd** [Coding-Coach/coding-coach#214]
# Issue

## Description

Right now the deployment to gh-page is done manually. This is not very efficient. The process of deployment should be automated. 

## Direct Requirements

1. Break down the build task to 4 stages - Lint, Test, Build and Deploy
2. If the branch is other than master skip the deploy stage
3. If the branch is master run the deploy stage

**Comment by linux-nerd** [comment]
@emmawedekind, @crysfel can you assign this issue to me 😄

**Comment by crysfel** [comment]
You are Abishek in Slack, right? Just making sure two different people are working on the same thing 😂

@emmawedekind we should add a field in slack to enter our github username. Not everyone uses the same name or avatar

**Comment by linux-nerd** [comment]
Hahaha thats right @crysfel

**Comment by tureey** [comment]
I actually don't use the same.. But my yoga profile picture is meaningful :laughing:

**Comment by emmawedekind** [comment]
Any update to this issue?

**Comment by linux-nerd** [comment]
@emmawedekind Not able to proceed due to lack of documentation. #215

**Comment by crysfel** [comment]
Closing...
