### ISSUE TITLE
Sign Up With Social Media (O-Auth) - Mobile

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#222]
![image](https://user-images.githubusercontent.com/7671983/48345268-e149b180-e677-11e8-8ead-84a1dfa24a7d.png)

**Comment by emmawedekind** [comment]
Assigned!

**Comment by crysfel** [comment]
@linux-nerd yeah, that sound good!

**Comment by linux-nerd** [comment]
@crysfel What is the difference between sign in with social media and signup with social media?

**Comment by crysfel** [comment]
It looks the same to me xD 

Not sure if @frederickalcantara already started. If not, you should take it and close one to avoid working on the same thing.

**Comment by tureey** [comment]
Well.. there is a lot of people that says that if you sign in with social media and you are not registered.. it created you an account....

I would say that the login/signup concept with social media has been merged. The only case it's different is when you want to do it manually.

**Comment by frederickalcantara** [comment]
I haven't gotten around it. You can take it.

**Comment by linux-nerd** [comment]
@crysfel Do we have a flow/documentation for this? How do we tend to authenticate?

**Comment by crysfel** [comment]
Jagadish K (Not sure what's his github user) is working on the backend to implement login/sigup with passport.

For the client side all we have to do is just redirect to the selected platform, receive the token and give it to the backend, if success redirect to dashboard, else show errors.

**Comment by linux-nerd** [comment]
I have started working on FB oAuth. @frederickalcantara, if you want to work on other oAuth, you can proceed.

**Comment by linux-nerd** [comment]
> How's this going?

Will resume the work from tomorrow.

**Comment by linux-nerd** [comment]
@crysfel Since oAuth with twitter needs to interact with backend API. I have started working on API to make it work.

Moreover, I feel we should move the logic to of storing the secret key/token for other auth on the API as well. 

I don't see anyone working on those API on the board. So, for the time being, I am working on it.

**Comment by linux-nerd** [comment]
@crysfel, @emmawedekind I am pausing until we have some discussion finalized on auth0/passport.js

**Comment by crysfel** [comment]
The backend team decided to go with oauth, therefore this task is no longer relevant. I'm sorry @linux-nerd 🤷‍♂️

**Comment by linux-nerd** [comment]
That's fine @crysfel  😎

**Comment by emmawedekind** [comment]
I will close this issue for now then :)
