### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#223]
- [ ]  A user can sign in to Coding Coach with their email address or social media accounts.
- [ ] A user can click the Forget Password Link to reset their password.

![image](https://user-images.githubusercontent.com/7671983/48345454-5ddc9000-e678-11e8-8480-cad279e941ef.png)

**Comment by praveen-me** [comment]
@emmawedekind I want to work on this. Is this issue available.

**Comment by emmawedekind** [comment]
So I believe this issue is actually the "epic" for the other issues beneath it.
https://github.com/Coding-Coach/coding-coach/issues/225
https://github.com/Coding-Coach/coding-coach/issues/222
https://github.com/Coding-Coach/coding-coach/issues/52

**Comment by emmawedekind** [comment]
Therefore, we don't need to complete this issue, thanks though! Feel free to comment on the other issues and see if people need help.
