### ISSUE TITLE
Sign In With Social Media

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#225]
- [ ] A user can sign in with social media accounts.

![image](https://user-images.githubusercontent.com/7671983/48345285-f1fa2780-e677-11e8-9f49-d56a4ddc6d28.png)

Sketch file: https://sketch.cloud/s/xVR5A

**Comment by frederickalcantara** [comment]
I would like to take in this task.

**Comment by crysfel** [comment]
@frederickalcantara all yours! Please remember to use tailwind for the styling ;)

**Comment by frederickalcantara** [comment]
I'm just curious, what do you think of using next js for the app? I think it would be great for SSR. If theres more pages it would be better for SEO purposes.

**Comment by crysfel** [comment]
We are using `react-snap` for SEO purposes, this will only apply for public pages such as the landing page.

**Comment by DanielRuf** [comment]
I miss GitHub as login option. ;-)

**Comment by tureey** [comment]
+1 :D Actually since we are developers.. I don't think anyone will log in with IG

**Comment by emmawedekind** [comment]
Yes feel free to add GH! These are just mock-ups :) Improvements are always welcome!

**Comment by emmawedekind** [comment]
Hi, what's the status?

**Comment by DanielRuf** [comment]
@emmawedekind who do you mean?

**Comment by emmawedekind** [comment]
Is there status on the development :)
