### ISSUE TITLE
Sign In & Sign Up Form Submission Loading Indicator

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#226]
A loading indicator should be shown on form submission.

Example behavior: https://codepen.io/mrrocks/pen/EiplA
(No changing gradient is necessary, just similar spinning style).

![image](https://user-images.githubusercontent.com/7671983/48345409-430a1b80-e678-11e8-8e67-d35b424fb8aa.png)

**Comment by bhupendra-nitt** [comment]
Can someone assign it to me?

**Comment by emmawedekind** [comment]
Hi, what's the status?

**Comment by bhupendra-nitt** [comment]
Hey, I somehow missed notification for this. Will pick it up now. Apologies for the delay.

**Comment by emmawedekind** [comment]
No worries thx

**Comment by bhupendra-nitt** [comment]
Guys, I will unassign myself from this issue as of now. I am just caught up with something at the moment.

**Comment by olegk101** [comment]
I can take it too

**Comment by emmawedekind** [comment]
Unassigned @bhupendra-nitt and assigned @linux-nerd since he posted first, but if you can't take it for some reason I'm happy to assign @olegk101 :)

**Comment by linux-nerd** [comment]
@crysfel Any idea how to use animation with tailwind?

**Comment by emmawedekind** [comment]
It's just normal CSS, right? @linux-nerd. Can't you just use keyframes?

**Comment by crysfel** [comment]
so far we've been creating plugins for custom css

**Comment by linux-nerd** [comment]
> It's just normal CSS, right? @linux-nerd. Can't you just use keyframes?

@emmawedekind I am using keyframes. I thought there is a way to deal with this in tailwind.

**Comment by linux-nerd** [comment]
> so far we've been creating plugins for custom css

I will sync up with you, once I get my component to a logical end. Right now I am struggling with styling the svg.

**Comment by linux-nerd** [comment]
@crysfel , @emmawedekind 
The Loader should be generic right? It can be used with other components as well. But, have de decided any minimum size of the spinner or the size of the spinner will be constant?

For example,
```
<Loader loaded={isLoading}>
  <p>Some text</p>
<Loader/>
<Button onClick={triggerLoader}>Trigger Loader</Button>
```

The spinner will appear in just one line of very limited height and width. Should we support this?

**Comment by emmawedekind** [comment]
Yes it should definitely be re-usable! Can we have different sizes? So spinner-large, spinner-normal, spinner-small?

**Comment by crysfel** [comment]
@linux-nerd let's a a `size` property to set the spinner size
