### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#227]
- [ ] A user can click the Forgot Password link to reset their password.

![image](https://user-images.githubusercontent.com/7671983/48345501-7c428b80-e678-11e8-97ac-dacf30dcb23e.png)

**Comment by kakaly** [comment]
@emmawedekind @crysfel - Can I take this one?

**Comment by emmawedekind** [comment]
@kakaly You have already received an invitation to join the organization. You have to accept it.

**Comment by kakaly** [comment]
@emmawedekind - Thanks! Got it. Sorry about that. I missed the email somehow.

**Comment by emmawedekind** [comment]
Wonderful! Assigned :)

**Comment by emmawedekind** [comment]
Hi, what's the status?

**Comment by kakaly** [comment]
@emmawedekind - PR is out. I will address the review comments by Friday. 

https://github.com/Coding-Coach/coding-coach/pull/266

**Comment by tureey** [comment]
I left some comments on the PR @kakaly tell me your thoughts! :smiley:

**Comment by kakaly** [comment]
@tureey - Yup! I ll share my thoughts on your comments. Sorry, I just got back from a vacation. :) Thanks for looking at it though.

**Comment by tureey** [comment]
It's okay! I hope you enjoyed the vacation :nerd_face:
