### ISSUE TITLE
Forgot Email - Send Reset Link To Email Address

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#228]
Once the Forgot Password form has been submitted, an email is sent to the user's email address with a reset link.

Email Text: "Uh oh, looks like you forgot your password! Click the link below to reset it and get back to Coding Coach!"

**Comment by crysfel** [comment]
@emmawedekind this issue should be transfer to the backend repo.

**Comment by emmawedekind** [comment]
Sure thing
