### ISSUE TITLE
Update Input Style

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#230]
![image](https://user-images.githubusercontent.com/7671983/48305204-c6b3f300-e526-11e8-9ba5-d90ff52f7f34.png)

**Comment by feysalikbal** [comment]
I would like to work on it.

**Comment by emmawedekind** [comment]
Added!

**Comment by crysfel** [comment]
@feysalikbal we don't have a `TextField` component yet, you should work on https://github.com/Coding-Coach/coding-coach/issues/125 first, I'm going to assign it to you ;)

**Comment by feysalikbal** [comment]
Thanks. I'm on it.

**Comment by crysfel** [comment]
We do have a [Textfield component](https://github.com/Coding-Coach/coding-coach/blob/develop/src/components/textfield/TextField.js), but is missing the styles defined in this task.

@feysalikbal let us know if you need any assistance with this.

**Comment by trent-boyd** [comment]
I've got some time this week to contribute. I'd be happy to take this on @emmawedekind. :)

**Comment by trent-boyd** [comment]
@emmawedekind Sure! I'll have some time later this week.

**Comment by crysfel** [comment]
@trent-boyd all yours!
