### ISSUE TITLE
Migrate the Button component to tailwind

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#232]
# Issue

## Description

The current `Button` component is using sass for the styles, we are now migrating to tailwind. We need to remove all the sass styles for the button and use tailwind instead.

Here are all the buttons we need to support: https://sketch.cloud/s/xVR5A/7yyVk08

**Comment by crysfel** [comment]
@emmawedekind can we add @msweeneydev to the organization to assign him this issue?

**Comment by tureey** [comment]
Good point @msweeneydev

**Comment by kakaly** [comment]
@crysfel - Please assign this to me

**Comment by kakaly** [comment]
I am considering, extracting custom components using @apply for each button type inside tailwind.css
and use them directly inside Button.js

@crysfel - Let me know if this design is okay.

**Comment by kakaly** [comment]
Submitted a PR: https://github.com/Coding-Coach/coding-coach/pull/265

**Comment by crysfel** [comment]
Thanks for contributing, I've left a few comments in your PR.

**Comment by crysfel** [comment]
Thanks for contributing!
