### ISSUE TITLE
Migrate the Footer component to tailwind

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#235]
# Issue

## ZenHub Issue

We need to remove all sass code for the Footer component and migrate it to tailwind.

Footer component:
https://github.com/Coding-Coach/coding-coach/blob/develop/src/components/footer/Footer.js

Design:
https://sketch.cloud/s/xVR5A

**Comment by sup-rith** [comment]
I would like to take this!

**Comment by crysfel** [comment]
All yours! Please ask @emmawedekind in slack to add you to the github organization in order for me to assign this issue to you.

You can start working on this now, once added to the org, I will just update the issue.

Thanks!

**Comment by tureey** [comment]
ping @sup-rith

**Comment by saravanaselvan** [comment]
@crysfel @tureey if this issue still not assigned, I would like to try it.

**Comment by tureey** [comment]
Hey @saravanaselvan, even though the task is not assigned here in Github _(I know we should have done it, sorry for not doing it yet and creating confusion)_ @sup-rith is working on it.

I did not know @emmawedekind already added him on the Github Group

**Comment by saravanaselvan** [comment]
Hey @tureey No problem. Thanks for letting me know. I will look for any other unassigned issues.

**Comment by rachelfranklin1** [comment]
hey @crysfel it looks like this issue is up for grabs again, can I take it? :)

**Comment by crysfel** [comment]
All yours! Thanks!

**Comment by rachelfranklin1** [comment]
just an update: almost finished! Just had a busy weekend! 😅 so will aim to get this finished by Weds at the latest!

**Comment by crysfel** [comment]
@rachelfranklin1 thanks!
