### ISSUE TITLE
Migrate Modal component to tailwind

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#236]
# Issue

## ZenHub Issue
The current Modal component is using SASS for styling, we need to remove all that code and use tailwind instead

**Comment by crysfel** [comment]
All yours!

**Comment by emmawedekind** [comment]
What's the status

**Comment by tureey** [comment]
Finished pending feedback from @crysfel https://github.com/Coding-Coach/coding-coach/pull/249
