### ISSUE TITLE
Migrate OverlayCookie component to tailwind

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#237]
# Issue

Migrate the OverlayCookie component to tailwind, don't forget to remove all SASS code

**Comment by dlofran2** [comment]
I'll go ahead and take this issue.

**Comment by crysfel** [comment]
All yours! 

*please ask @emmawedekind to add you to the github organization in order for me to assign the issue to you.*

**Comment by tureey** [comment]
ping @dlofran2

**Comment by dlofran2** [comment]
Hi @tureey, if you want to take this instead thats fine.  Been having to work a lot of overtime this week so I haven't had much free time to contribute.

**Comment by tureey** [comment]
I'll get it then 👍

**Comment by emmawedekind** [comment]
What's the status here? I think the PR needs a review right?

**Comment by emmawedekind** [comment]
Closes #253

**Comment by tureey** [comment]
Yes, thank you for tagging the issue so it will be closed automatically @emmawedekind
