### ISSUE TITLE
Migrate Panel component to tailwind

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#238]
# Issue

The Panel component is using SASS for styling, we need to remove all that code and migrate it to tailwind.

**Comment by dlofran2** [comment]
Hi @crysfel, mind if I take this issue?

**Comment by crysfel** [comment]
All yours! Please join [our slack](https://coding-coach.slack.com/) and ask @emmawedekind to add you to the organization, that way I can assign it to you.

But you can start working on this. Looking forward to see your work!
