### ISSUE TITLE
Move custom tailwind plugins out of tailwind.js file

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#251]
# Issue

## Description

We have several custom plugins inside `tailwind.js` file, let's move them out from there to `src/theme/plugins`. 

Once they are in different files we should import them and add it to `tailwind.js` like this:

```
plugins: [
    require('tailwindcss/plugins/container')({
      // center: true,
      // padding: '1rem',
    }),
   require('src/theme/plugins/panel')(),
   require('src/theme/plugins/diagonalbg')(),
   // etc...
  ],
```

**Comment by klazbaba** [comment]
May I have this one?

**Comment by klazbaba** [comment]
@crysfel, please how do I test this to know if what I have done works? I would love to test before making a PR.

**Comment by klazbaba** [comment]
Not programming test. I just want to see it run before making my PR. Thanks very much @tureey

**Comment by klazbaba** [comment]
I keep running into the error 'require(...) is not a function.'

**Comment by tureey** [comment]
Can you provide please pictures of the error in the console? @klazbaba 
Try deleting the `node_modules` folder and installing again.

**Comment by klazbaba** [comment]
![require error](https://user-images.githubusercontent.com/34392299/50647701-8e0a2600-0f79-11e9-904d-9f9e697a3307.PNG)
![error source](https://user-images.githubusercontent.com/34392299/50647715-95313400-0f79-11e9-81ec-f7279e58b999.PNG)

**Comment by klazbaba** [comment]
@tureey, that is the error and its source.

**Comment by emmawedekind** [comment]
I've added you to the org - will assign once it registers

**Comment by klazbaba** [comment]
Alright @emmawedekind, thanks.

**Comment by tureey** [comment]
@klazbaba Sometimes I have this error and I just remove the `node_modules` folder like I said and reinstall everything. Have you tried?

Have you compilated the translations? I had problems making it worked and I had to compile them as well.


If not, I have no idea

**Comment by klazbaba** [comment]
Yes, I had removed and reinstalled the node modules. As for compiling the
translations, how do I achieve that please?

**Comment by tureey** [comment]
As you can see @klazbaba  in the picture there are some scripts that do this. You can:
`yarn i18n-compile` to compile the translations
`yarn start` will *extract* and *compile* the translations and *build* the `css` and the `bundle`.

*I hope this is the solution. If not, wait for @crysfel because in matter of errors I'm pretty bad sorry.*

![1](https://user-images.githubusercontent.com/16169890/50790518-6a1f4b00-12bf-11e9-9fe8-c639d53ac760.png)

**Comment by crysfel** [comment]
@klazbaba based on the error and the source code you are showing... it looks to me that the problem might be the way you are exporting inside each plugin.

Without seeing that code it's difficult to asses, but maybe you don't need the extra `()` in each require, try just this:

```
plugins: [
  require('./src/theme/plugins/color'),
  require('./src/theme/plugins/height'),
  // etc...
],
```

In order to test all you have to do is `yarn start` and the app should load as usual.
