### ISSUE TITLE
Dashboard - Header

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#255]
![image](https://user-images.githubusercontent.com/7671983/49695002-5f747780-fb94-11e8-88d0-45b46fede2f4.png)

![image](https://user-images.githubusercontent.com/7671983/49695110-fbeb4980-fb95-11e8-96e6-b82a2b584c06.png)

- [ ] Gradient background
- [ ] Coding coach logo in top right corner
- [ ] "Modal" type layover for new messages
- [ ] "Open" button which leads to the messages panel
- [ ] "Let's go" button which leads to the mentorships panel

## Text

**Text for account with messages**
"You have X new messages!"

**Text for account with messages (Button)**
"Open"

**Text for account with no messages (Button)**
"Let's go"

**Text for account with no messages (Mentor)**
"Welcome back! Head over to the mentorships tab to find a new mentor or mentee!"

**Text for account with no messages (Mentee)**
"Welcome back! Head over to the mentorships tab to find a new mentor!"

# Assets
All icons & color codes can be found on the Sketch cloud: https://sketch.cloud/s/xVR5A/p/dashboard

**Comment by tureey** [comment]
I love the design!! 😍

**Comment by tureey** [comment]
May I have this one?

**Comment by tureey** [comment]
I commented in my PR https://github.com/Coding-Coach/coding-coach/pull/267: **I am working on it.**

Things left:
* Wait for the components PR #259 to be merged so I can use the media included in
* Generate the translation for `Dashboard` (I executed compile and extract and still not working) @crysfel  Any idea?
* Use the same `spacing size` for the padding of the Header and the `width` not used by the notification
* Component tests

**Comment by tureey** [comment]
@emmawedekind Perfect! :+1:

**Comment by emmawedekind** [comment]
Any update on this @tureey ? :)

**Comment by crysfel** [comment]
#259 has been merged 🎉

**Comment by tureey** [comment]
@crysfel thank you!!!!! 🎉
