### ISSUE TITLE
Dashboard - Notifications

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#256]
![image](https://user-images.githubusercontent.com/7671983/49695085-aa42bf00-fb95-11e8-848d-6cec64c308ca.png)
![image](https://user-images.githubusercontent.com/7671983/49695088-b9c20800-fb95-11e8-8ab2-ed160454d073.png)

- [ ] Notifications appear in a list (if there are any)
- [ ] If no notifications are present, add the text for no notifications (below).

## Text

**Text for account with no notifications**
"You don’t have any notifications right now. Check back soon!"

# Assets
All icons & color codes can be found on the Sketch cloud: https://sketch.cloud/s/xVR5A/p/dashboard

**Comment by moyamanuel** [comment]
May I take this issue?

**Comment by alexluong** [comment]
I'd be happy to take this up if you're still enjoying your holiday, @moyamanuel.

**Comment by moyamanuel** [comment]
Hey @emmawedekind -- I just saw the 'Blocked' was removed from this task. I'll get working on this ASAP!

**Comment by emmawedekind** [comment]
Thanks!
