### ISSUE TITLE
Components - Navigation

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#257]
![image](https://user-images.githubusercontent.com/7671983/49815509-360e4400-fd6c-11e8-98ed-54dce6b81282.png)

![image](https://user-images.githubusercontent.com/7671983/49815429-0c551d00-fd6c-11e8-8782-72bd9181be22.png)

- [ ] Bottom navigation for mobile devices

- [ ] Side navigation for tablets & desktop

- [ ] Active page icon is in full color

- [ ] Inactive page icons are grayed out

- [ ] Each icon must have an associated aria-label for accessibility

# Assets
All icons & color codes can be found on the Sketch cloud: https://sketch.cloud/s/xVR5A/p/navigation

**Comment by nitish24p** [comment]
👋 can i?

**Comment by emmawedekind** [comment]
Sure thing! Assigned, thanks!

**Comment by crysfel** [comment]
This issue depends on #259 ;)

**Comment by nitish24p** [comment]
@crysfel can we have a quick discussion on the implementation.. whether to use a config object or compound components for this

**Comment by crysfel** [comment]
That's a good question, what about something like this:

```
<MainNav>
  <Option to="/app/dashboard" icon={DashboardIcon} label="Dashboard" />
  <Option to="/app/inbox" icon={MessagesIcon} label="Messages" />
  ....
</MainNav>
```

Internally the `Option` component will render the link, icon and label.

**Comment by nitish24p** [comment]
Cool.. i had also thought of something like this
```javascript
const sidebarConfig = [
  {
    name: 'Dashboard',
    icon: 'path/to/icon'
    link: '/dashboard,
    props: {
      someProps: foo
    }
  },
  {
    name: 'Messages',
    icon: 'path/to/icon'
    link: '/messages,
    props: {
      someProps: foo
    }
  }
]
```

```jsx
<Sidebar config={sidebarConfig} />
```

But i guess your method is declarative and easier to understand.

**Comment by emmawedekind** [comment]
Please note updated designs with labels for menu items!

**Comment by nitish24p** [comment]
Should be done by the weekend.. this one depends on https://github.com/Coding-Coach/coding-coach/issues/259 so for the moment i've made placeholder icon components

**Comment by msweeneydev** [comment]
How are we doing with this now that #259 has been merged?

**Comment by tureey** [comment]
I'm gettin it

**Comment by msweeneydev** [comment]
He's got it! 💯
