### ISSUE TITLE
Components - Notifications

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#258]
![image](https://user-images.githubusercontent.com/7671983/49695125-51bff180-fb96-11e8-9fa9-4648fc25d0b0.png)

- [ ] Mentorship notifications have blue edge

- [ ] Account notifications have green edge

- [ ] Error and issue notifications have red edge

- [ ] Selected notification has clear button appear in top right corner and a box shadow effect

# Assets
All icons & color codes can be found on the Sketch cloud: https://sketch.cloud/s/xVR5A/p/notifications

**Comment by emmawedekind** [comment]
Sure, I'll assign you! Looks like you weren't added to the organization, so I went ahead and added you. I'll assign you to the issue once your addition has been registered. Thanks so much!

**Comment by alexluong** [comment]
@emmawedekind Thanks for the invitation. I joined the organization.

**Comment by crysfel** [comment]
@alexluong all yours! You should use storybook for this, as we don't have the dashboard ready.

**Comment by alexluong** [comment]
@crysfel Thanks for the tips. I've been using storybook for it. Can you check out my ongoing PR #261? I got a few questions over there!

**Comment by alexluong** [comment]
Let's close this issue. I'd love to help out more if there's any other tasks!

**Comment by crysfel** [comment]
@alexluong thanks for contributing!
