### ISSUE TITLE
Components - Icons

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#259]
![image](https://user-images.githubusercontent.com/7671983/49695137-83d15380-fb96-11e8-8adb-2957a5145851.png)

# Assets
All icons & color codes can be found on the Sketch cloud: https://sketch.cloud/s/xVR5A/paKjK7A

# Details
Given that we are going to use our own custom svg icons, we need to remove `@fortawesome` from our dependencies: https://github.com/Coding-Coach/coding-coach/blob/develop/package.json#L28-L31

We already have an `Icon` [component](https://github.com/Coding-Coach/coding-coach/blob/develop/src/components/icon/Icon.js) to render svg icons, let's use this approach for all new icons.

This task also includes migrating the current icons in the home page from `fortawesome` to the new `Icon` component that we have.

*Edit*: The design contains two states for the icons (active, inactive), that should be handled by the navigation component (We don't have it yet), this task doesn't include that. Only adding the icons to our icons catalog, we might want to create a storybook for all the available icons we already have.

**Comment by steoneill** [comment]
I can take this if that’s ok? :)

**Comment by steoneill** [comment]
@emmawedekind could you add me to the organisation please? :)

**Comment by steoneill** [comment]
@crysfel  i believe i've been added now :)

**Comment by emmawedekind** [comment]
Hi, what's the status @steoneill

**Comment by tureey** [comment]
@steoneill 
![image](https://user-images.githubusercontent.com/16169890/50730152-60bea300-1146-11e9-9401-acee41b5f4ce.png)

**Comment by steoneill** [comment]
Hi guys! 

Sorry for the delay, had a very sick 6 month old so haven't progressed as quick as I thought! 

Will get this pushed ASAP!

(Feel free to move it to someone else, i'd 10000% understand)

**Comment by trent-boyd** [comment]
@emmawedekind I don't mind taking this over so @steoneill can focus on taking care of his stick kiddo. 👶 😷 

I think though, that I might need the actual SVG assets exported from Sketch. I don't see a way to access them on the link you posted. Or maybe I need to sign up for Sketch cloud?

@crysfel, do you think we could use [this cool new feature](https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files#adding-svgs) of `react-scripts` 2.0 to automagically import SVG icons as React components? Looks like it could be pretty simple to add new icons in the future.

**Comment by tureey** [comment]
> @emmawedekind I don't mind taking this over so @steoneill can focus on taking care of his sick kiddo.  
> 
> I think though, that I might need the actual SVG assets exported from Sketch. I don't see a way to access them on the link you posted. Or maybe I need to sign up for Sketch cloud?
> 
> @crysfel, do you think we could use [this cool new feature](https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files#adding-svgs) of `react-scripts` 2.0 to automagically import SVG icons as React components? Looks like it could be pretty simple to add new icons in the future.

ow... I did not know about its existence! It's cool

**Comment by crysfel** [comment]
> @crysfel, do you think we could use [this cool new feature](https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files#adding-svgs) of `react-scripts` 2.0 to automagically import SVG icons as React components? Looks like it could be pretty simple to add new icons in the future.

We are using it in some parts of our application, however... for the icons we do have react components for that where we just define the vectors in a variable or if there are several elements we can define as many nodes as needed.

https://github.com/Coding-Coach/coding-coach/blob/develop/src/components/icon/Twitter.js

**Comment by trent-boyd** [comment]
@crysfel: I saw that, but I don't think the approach in `Icon.js` will work for multicolored icons, which will have more multiple paths than won't fit into the `vectors` prop.

I don't have any of these SVG assets yet, but [here's an example](https://gist.githubusercontent.com/trent-boyd/8928bb50e50c31dda546aaae63221a63/raw/2b61e03d8e906e05fdd7b85e415ca858fb455e1f/lightbulb.svg) from an old project I worked on.

**Comment by emmawedekind** [comment]
Can you grab the assets from Sketch Cloud? That's the easiest way @trent-boyd

**Comment by crysfel** [comment]
The Icon component also accepts any number of children, specifically for this scenario:

```
<Icon {...props}>
   <g path="abc....." />
   <g path="abc....." />
   <g path="abc....." />
</Icons>
```

**Comment by trent-boyd** [comment]
Hmm. Sketch Cloud requires me to have Sketch to get these SVGs out of the document. Hopefully I can resolve this before the demo is up. I've exported these each on an 80x80 artboard. If there's some standard for this, let me know.

![image](https://user-images.githubusercontent.com/1660908/50943912-f1052c80-1453-11e9-896e-f2cb07a00bf2.png)

**Comment by trent-boyd** [comment]
@crysfel: Let me know what you think about this. It's probably easier to focus on [this commit](https://github.com/Coding-Coach/coding-coach/pull/291/commits/5029c29e554cf6671fa48300db476c50b9bf264c) since the raw SVGs make a lot of green in the diff view.

**Comment by emmawedekind** [comment]
If you need assets, please message me directly on Slack :)

**Comment by emmawedekind** [comment]
I put all the SVG icons up on the Invision board! Let me know if you can't download them for whatever reason: https://projects.invisionapp.com/boards/UF3Q7E6QEZM/

**Comment by emmawedekind** [comment]
Hi... any update on this @trent-boyd ? :) We need this to move forward with other tasks!

**Comment by emmawedekind** [comment]
Linked with PR #291

**Comment by trent-boyd** [comment]
@emmawedekind: Sorry about that. I've been prepping for some upcoming interviews lately, and haven't had as much time as I'd like to contribute. Hoping to find some time in the next couple of days. 🤞

**Comment by emmawedekind** [comment]
Great thanks! :) Just please update the issue when you're ready!

**Comment by trent-boyd** [comment]
Hey @emmawedekind, I'm not adding a specific `Notifications` icon (see above) since the red numbered indicator should be dynamic and can be created pretty easily with plain HTML & CSS.

**Comment by emmawedekind** [comment]
Super thanks!
