### ISSUE TITLE
Add mailing list modal to landing page

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#269]
We need a way to capture user's emails. Please embed this modal from Mail Chimp!

`<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us19.list-manage.com","uuid":"98c69835a5abaf1759e7618ec","lid":"3f9f14ba16","uniqueMethods":true}) })</script>`

**Comment by alizand1992** [comment]
@emmawedekind I'd like to try this.

**Comment by emmawedekind** [comment]
Great! Not sure if you're in the org... I can add you.

**Comment by alizand1992** [comment]
Got the invite, and accepted. Thank you

**Comment by crysfel** [comment]
Merged and deployed!
