### ISSUE TITLE
Remove PayPal button from code

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#272]
We will be using Patreon (which Emma will provide a design/UX & Issue for) so we must remove the PayPal  donation button from the code.

**Comment by haroonKhan-10p** [comment]
I will take this up on the weekend.

**Comment by mazma1** [comment]
I'll like to work on this

**Comment by emmawedekind** [comment]
Perfect I'll assign!

**Comment by trent-boyd** [comment]
@haroonKhan-10p: Make sure to remove the `REACT_APP_PAYPAL_DONATE_BUTTON_ID` env var from `.env.example` when you commit, since we be using that anymore.
