### ISSUE TITLE
Remove Instagram from landing page

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#274]
It doesn't make sense to keep up with an IG account for CC. I'd like to remove it.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/7671983/50677981-e6363c00-0ffc-11e9-9c90-10b9bbfa678c.png">

**Comment by msweeneydev** [comment]
I'll take this one please :+1:

**Comment by msweeneydev** [comment]
Just to clarify, would you like to remove the IG account from just this section or remove all reference of it from the code?

**Comment by tureey** [comment]
I would say to remove it completely. But wait her answer.

Anyway, we have it on `git` so................... haha

**Comment by msweeneydev** [comment]
Agreed @tureey, I can't see why you'd leave any behind but you never know! Let us know your thoughts @emmawedekind
