### ISSUE TITLE
Remove Slack organization link from landing page

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#275]
The Slack organization link is reset each time you share it, so we must remove it from our page.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/7671983/50677995-ff3eed00-0ffc-11e9-89e2-28ed2c7e6150.png">

**Comment by nero2009** [comment]
I'd take this, 
what should I replace it with? or should I just yank off the "feel free to join our slack organization"

**Comment by trent-boyd** [comment]
@emmawedekind: Tangentially related to this ticket, but maybe it's an option to consider. [Slackin](https://github.com/rauchg/slackin) is something we could run on a subdomain to have a more open Slack invite initiative. It would end up looking like [this invite page at Open Austin](https://slack.open-austin.org/). Maybe worth investigating.

**Comment by crysfel** [comment]
@nero-adaware all yours, it'd be nice if you can implement something like @trent-boyd said. Can you take a look into that?

**Comment by trent-boyd** [comment]
@crysfel: I think Slackin would require some backend work as well. Looks like it works with Express, so it might be its own separate app that runs on Heroku. It's a good deal of work to implement.

**Comment by nero2009** [comment]
> 
> 
> @nero-adaware all yours, it'd be nice if you can implement something like @trent-boyd said. Can you take a look into that?

Ok

**Comment by nero2009** [comment]
@crysfel I need to be an admin user so I can generate an slack API test token. [https://github.com/rauchg/slackin#tips](url)

**Comment by emmawedekind** [comment]
I'm not comfortable handing out Admin access to Slack - is there a different way to proceed?

**Comment by emmawedekind** [comment]
And can we please remove the link for now? I keep getting messages that it's broken.

**Comment by nero2009** [comment]
> 
> 
> I'm not comfortable handing out Admin access to Slack - is there a different way to proceed?

The only other option is to create a new user and give the user admin access.

**Comment by nero2009** [comment]
> 
> 
> And can we please remove the link for now? I keep getting messages that it's broken.

Ok I will

**Comment by tureey** [comment]
But wait, can't @emmawedekind generate the `api_key` and give it to you? I'm missing something

**Comment by nero2009** [comment]
> 
> 
> But wait, can't @emmawedekind generate the `api_key` and give it to you @nero2009 ? I'm missing something

Yeah @emmawedekind  can

**Comment by nero2009** [comment]
Hi @crysfel I think this issue should still be open until we create  the slack invite page.

**Comment by trent-boyd** [comment]
I think the Slack invite page warrants enough work to be an issue itself.

**Comment by emmawedekind** [comment]
We have a new issue for it, I'll push to get it merged ASAP https://github.com/Coding-Coach/coding-coach/issues/298 @moshfeu

**Comment by moshfeu** [comment]
Joined, thanks!
