### ISSUE TITLE
When modal is open, user can still scroll the background

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#276]
If a modal is open, a user should not be able to scroll behind it.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/7671983/50678038-24336000-0ffd-11e9-8f43-6a03ac04541c.png">

**Comment by flagoon** [comment]
I would like to take this on :)

**Comment by tureey** [comment]
@emmawedekind Could we add @flagoon to the organization please? Thank you! <3

**Comment by flagoon** [comment]
Ah sorry, I didn't know I had to be in the organization. I just thought it's open for anyone who wants to contribute to open source (I'm trying to get into it).

**Comment by tureey** [comment]
It is, but since we want to track and organize the tasks and try to distribute work, we thought that having an organization could help us to be organized

**Comment by flagoon** [comment]
I had some time this weekend, but I can't promise I will have time this week. Please, don't consider me for this task anymore ;) Maybe later I will read how to join the organization and that way contribute :).

**Comment by tureey** [comment]
@flagoon OK!

** This task is not assigned to anyone yet so**

**Comment by pitakill** [comment]
I want to take this task. :-)

**Comment by crysfel** [comment]
@pitakill all yours! You can start working on this now and as soon as @emmawedekind adds you to the org I can officially assign it to you.

Also, go to slack and ask @emmawedekind to add you to the organization.

**Comment by trent-boyd** [comment]
So is this just adding `overflow-hidden` to the body class list, or should we consider a more complex situation to handle the edge cases like older iOS versions?

**Comment by tureey** [comment]
I was thinking about adding `overflow-hidden`. Right now is the most pragmatic thing to solve this IMHO

**Comment by tureey** [comment]
Since @flagoon refused... Could you add @pitakill to the organization too please @emmawedekind ?

**Comment by emmawedekind** [comment]
Added
