### ISSUE TITLE
Remove .env file from .gitignore to ease installation & setup

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#278]
Currently after cloning, users have to remove the `.example` extension from the `.env` file. This is annoying. Let's just remove `.env` from the `.gitignore`.

**Comment by jagzviruz** [comment]
It wouldn't be advisable to allow committing .env files all the time. 
We can do a one time force commit for the file.

**Comment by trent-boyd** [comment]
I'd like to take this!

I kind of agree with @jagzviruz. `.env` files are usually for things that might change on a per-environment basis, but we're kind of using them as a dictionary. I don't think our social links need to be there, so could we just keep them defined in `constants.js`?

``` js
social: {
  // we could just remove everything before and including the ||
  FB_URL: process.env.REACT_APP_FACEBOOK_URL || 'https://www.facebook.com/codingcoachio/',
  INSTA_URL: process.env.REACT_APP_INSTA_URL || 'https://www.instagram.com/codingcoach_io/',
  TWITTER_URL: process.env.REACT_APP_TWITTER_URL || 'https://twitter.com/codingcoach_io',
  GITHUB_URL: process.env.REACT_APP_GITHUB_URL || 'https://github.com/Coding-Coach/coding-coach',
},
```

For the remaining variable (`NODE_PATH`), we could leave it defined there or prefix all our our scripts with it in `package.json` (e.g. `"build:app": "react-scripts build"` becomes something like`"build:app": "cross-env NODE_PATH=src/ react-scripts build"`). It's a little verbose to have it defined so many times, so I'm open to more input on that.

**Comment by crysfel** [comment]
@emmawedekind I wouldn't recommend that, is only a one time thing and is well documented in the readme.

Later one we are going to have the facebook app id and other values to support oauth, those values will depend on the instance the app is running, staging, production, local.

@trent-boyd yes, we only have a couple things that are unlikely to change and probably we can just define them right in the config file.

**Comment by trent-boyd** [comment]
> Same here, I usually configure webpack from scratch xD

You and me both, bud. Lots of people hate it, but I kinda like it. :)

**Comment by darrenvong** [comment]
Thought I'd leave a reference to facebook/create-react-app#2403 as it seems relevant to this discussion, where Dan Abramov supports committing `.env` file for convenience and the fact you can't store real secrets in the client app.

**Comment by crysfel** [comment]
@emmawedekind no hehehehe but... in order to help people get up and running easier (In case they didn't follow the README) let's commit the `.env` file.

This issue is open for anyone to take, it's quite simple, just remove the `.env` from the `.gitignore` :)

**Comment by becoming-software-engineer** [comment]
If trent-boyd is not taking this one, may I take?

**Comment by trent-boyd** [comment]
@becoming-software-engineer: I've got some other tickets to work, so feel free to take this. :)

**Comment by becoming-software-engineer** [comment]
Thanks, @trent-boyd.
@crysfel could you please assign this issue to me?

**Comment by emmawedekind** [comment]
I already invited you @becoming-software-engineer, you have to accept the invite :)
