### ISSUE TITLE
Privacy policy needs fleshing out

### ISSUE THREAD

**Issue by ArtOfCode-** [Coding-Coach/coding-coach#286]
The current privacy policy is just a skeleton:

> Coding Coach ("us", "we", or "our") operates the website and the Coding Coach mobile application (the "Service").
>
> This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. Our Privacy Policy for Coding Coach is managed through Free Privacy Policy.
>
> We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.

This needs fleshing out to be an actual privacy policy. If we're trying to be GDPR compliant, that needs to cover:

 - Who is collecting the data?
 - What data is being collected?
 - What is the legal basis for processing the data?
 - Will the data be shared with any third parties?
 - How will the information be used?
 - How long will the data be stored for?
 - What rights does the data subject have?
 - How can the data subject raise a complaint?

This may well need to wait until more of the application is completed to be able to answer some of these questions, but it nonetheless needs to be done; I'm throwing an issue here so that we remember it.

**Comment by JamieBort** [comment]
May I be assigned to this one?

**Comment by emmawedekind** [comment]
Absolutely! @JamieBort
