### ISSUE TITLE
Link to join Slack at ReadMe file should open join page

### ISSUE THREAD

**Issue by erolaliyev** [Coding-Coach/coding-coach#287]
# Issue

## ReadMe Issue

[ReadMe](https://github.com/Coding-Coach/coding-coach/blob/develop/README.md)

## Description

Link to join Slack workspace in ReadMe file is a link to sign in page of the workspace. I think it will be less confusing if it is replaced by link for sign up page which is this [one](https://coding-coach.slack.com/join/shared_invite/enQtNDYxNTcwMjk4MDcwLThiZjY1MTM2YTU1YzM2MGI1N2Y1NDI3ZGM1MGRhNjdiZjU0MzE1YjMxZjdlZmVlNDdhNmFhN2RhNGIxZmE1YTI)

**Comment by trent-boyd** [comment]
According to @emmawedekind, those links are single-use only (or something like that). We should probably remove them along with the work in #275.
