### ISSUE TITLE
Modals is shown under the Cookies Banner

### ISSUE THREAD

**Issue by tureey** [Coding-Coach/coding-coach#288]
## Steps to Reproduce
1- Remove cache
2- Low resolutions
3- Open the cookies policy

## Screenshot
![1](https://user-images.githubusercontent.com/16169890/50863162-19caea80-139e-11e9-9b58-7c2710666974.png)

**Comment by trent-boyd** [comment]
I thought this was by design. 🤷‍♂️

**Comment by tureey** [comment]
There is no way to accept though @trent-boyd hahaha my bad I should have seen it before!

**Comment by crysfel** [comment]
there's a `z-index` mapping on tailwind: https://tailwindcss.com/docs/z-index

Maybe we should consider renaming them?

**Comment by crysfel** [comment]
@emmawedekind no one has taken this issue, is open for anyone who want to work on this :)

**Comment by linux-nerd** [comment]
@emmawedekind  I can try

**Comment by linux-nerd** [comment]
@crysfel, @emmawedekind Raised a [PR](#296)

**Comment by emmawedekind** [comment]
Woohoo thanks!
