### ISSUE TITLE
Seeing scroll bar for login modal on a bigger monitor

### ISSUE THREAD

**Issue by kakaly** [Coding-Coach/coding-coach#295]
# Issue

## Screenshot
![cc](https://user-images.githubusercontent.com/7032778/51065026-971d7780-15b7-11e9-8b1f-3a773adadeac.PNG)

## Steps to Reproduce

Open codingcoach.io/auth/login on firefox using a bigger monitor

**Comment by alizand1992** [comment]
@emmawedekind I'm having trouble finding the repo on ZenHub so I'll just post here. I wanted to take this issue.

**Comment by crysfel** [comment]
@alizand1992 all yours! Let me know if you need any help

**Comment by tureey** [comment]
feel free to ask me too if you need @alizand1992

**Comment by alizand1992** [comment]
@crysfel @tureey 

I've narrowed down the issue to Panel.js > line 51 > `overflow-y-auto` 

Running on the latest develop branch on dev environment I get:

![screen shot 2019-01-16 at 6 03 58 am](https://user-images.githubusercontent.com/14100240/51253937-9b99b580-1954-11e9-82d8-097e90ca1093.png)

however looking at live I get:

![screen shot 2019-01-16 at 6 04 06 am](https://user-images.githubusercontent.com/14100240/51253950-ab18fe80-1954-11e9-9919-159173ed61df.png)

The interesting thing is that both live and dev have that class added.

I am wondering if the precompiled assets need to be updated on live?

**Comment by swissarmykirpan** [comment]
@crysfel are we not moving to auth0 and hosted pages? https://auth0.com/docs/hosted-pages/login

**Comment by alizand1992** [comment]
@crysfel  @tureey @swissarmykirpan I haven't heard anything back in a few days so I just wanted to touch base to see if this issue is necessary (based n @swissarmykirpan's comment), if it still needs to be fixed please see my comment above.

**Comment by tureey** [comment]
I'll check and try to solve this on my computer once I finish work. Now it's 7.35am, at 6-7pm. I was traveling sorry for not replying. I'll see what I can do then @alizand1992

**Comment by emmawedekind** [comment]
We have the channel cc33-signup going in Slack now. Is that where this discussion will be taking place?

**Comment by crysfel** [comment]
@alizand1992 I'm going to deploy the latest in dev tonight, my guess is the live version is running an old version, we'll see.

**Comment by alizand1992** [comment]
As I had suspected the issue has been resolved. @crysfel please close this this issue.

![screen shot 2019-02-05 at 6 32 45 am](https://user-images.githubusercontent.com/14100240/52280099-e1bcb600-290f-11e9-9498-1759ef437ea9.png)

**Comment by crysfel** [comment]
Glad to hear!
