### ISSUE TITLE
Add Slack organisation link to landing page

### ISSUE THREAD

**Issue by nero2009** [Coding-Coach/coding-coach#298]
# Issue
Add slack link to landing page

## Description
There were complaints that the slack link resets every time we share it so it had to be removed, now there is a working link.
https://join.slack.com/t/coding-coach/shared_invite/enQtNTE2NDY4NTczNzE0LTMyOTAyZTFiYjE4OTUzYjgwYzk5MzlmYjgwNjUyNDZlZGY3NGVhYmU1NjdmZDQ3MmQ3YjRhYjJkMjM4OTYwNDA

## Screenshot
![alt text](https://user-images.githubusercontent.com/7671983/50677995-ff3eed00-0ffc-11e9-89e2-28ed2c7e6150.png)

**Comment by kakaly** [comment]
@crysfel , @emmawedekind - Can I take this one?

**Comment by crysfel** [comment]
Sure! Apparently that links doesn't expire, let's see if that's true xD

**Comment by emmawedekind** [comment]
This is awesome!! Thanks so much @nero2009  You rock!

**Comment by emmawedekind** [comment]
Let's get this merged ASAP :)

**Comment by emmawedekind** [comment]
@kakaly did you want to take this still?

**Comment by moshfeu** [comment]
Joined, thanks!

**Comment by kakaly** [comment]
@emmawedekind - Yup! Sorry I was sick last 2 days. I ll submit a PR by tomorrow or day after

**Comment by crysfel** [comment]
@kakaly I just created a PR for this, will deploy tonight. Hope you feel better!

**Comment by kakaly** [comment]
This is great! Thanks @crysfel for filling me in.

**Comment by emmawedekind** [comment]
Thanks @crysfel
