### ISSUE TITLE
How to signup/login ?

### ISSUE THREAD

**Issue by danedavid** [Coding-Coach/coding-coach#305]
# Issue

I go to [codingcoach.io](https://codingcoach.io/), and I don't know how to login or signup for this. I can't find any links for the same.

**Comment by crysfel** [comment]
We are currently working on building the platform, for now you can join us in slack: https://join.slack.com/t/coding-coach/shared_invite/enQtNTE2NDY4NTczNzE0LTMyOTAyZTFiYjE4OTUzYjgwYzk5MzlmYjgwNjUyNDZlZGY3NGVhYmU1NjdmZDQ3MmQ3YjRhYjJkMjM4OTYwNDA
