### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by corinneling** [Coding-Coach/coding-coach#310]
# Issue

## Description

* Add a code of conduct to the readme
* Clearly communicate the following:
   * What is not acceptable as a member of coding coach
   * What will happen if the CoC is violated
   * Where users can report - will most likely be related to #44 
   * How coding coach will respond to a report

**Comment by corinneling** [comment]
I'll take this one

**Comment by emmawedekind** [comment]
Hey @corinneling ! We could use this more than ever! Any updates? :)

**Comment by corinneling** [comment]
@emmawedekind  yeah 🙂  i have it all written out, and I can try and make a PR today.

**Comment by emmawedekind** [comment]
Hi @corinneling any update?

**Comment by corinneling** [comment]
@emmawedekind here's the PR for the CoC. I still have to figure out how to get the tests to pass, but I think it could still be reviewed. Thank you for your patience with this!

**Comment by emmawedekind** [comment]
Thanks!

**Comment by crysfel** [comment]
I've deployed this to production, thanks for contributing!
