### ISSUE TITLE
Add text to the Code of Conduct

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#314]
# Issue
## Description

Adding a clause to prevent cheating on technical interview assessments.

## Screenshot

Add this content below the list of harassment: 

"We value integrity here at Coding Coach. As such, mentees may not ask for solutions to technical interview take home assessments. We're happy to mentor you in the process of solving difficult questions, but will not provide you with solutions to your assessments as they are meant to reflect your personal skill set."

![image](https://user-images.githubusercontent.com/7671983/55153254-4945f380-5152-11e9-9662-6205e010ba0c.png)

**Comment by splinterific** [comment]
Happy to have a look unless someone else wants it :)

**Comment by Sayrai** [comment]
I want!! :)

**Comment by emmawedekind** [comment]
You got it @splinterific

**Comment by emmawedekind** [comment]
Sorry @sayrai !

**Comment by Sayrai** [comment]
> Sorry @Sayrai !

it's fine
