### ISSUE TITLE
Add "How it works" section to the homepage

### ISSUE THREAD

**Issue by marvhock** [Coding-Coach/coding-coach#316]
# Issue
Adding a simple and short "how it works" section to the homepage (startpage).
## Description
With this issue, I want to address a problem which will prevent potential mentors and mentees to actually use Coding Coach, even when they could have the motivation to. 

The Coding Coach homepage only explains "what" and not "how" it works, making users feel somewhat lost (I felt so - also see [thread in Slack](https://coding-coach.slack.com/archives/CCT9D2TUN/p1554043861090600)). **Especially for first-visitors on the homepage, who will decide if they stay or leave, a short description on the homepage should let users imagine the basic process.**

So, additional to explaining what Coding Coach does, a "how it works" section on the homepage should explain to both target groups (mentors and mentees) how they can actually take action. I suggest something similar to writing this:

> You are looking for a mentor? 1: Find a mentor on the [mentors list](https://mentors.codingcoach.io/). 2: Contact the mentor by his/her contact option. 3: The mentor will respond, as soon as your message is read.
> 
> You want to become a mentor? 1:Follow [this guide](https://github.com/Coding-Coach/find-a-mentor/blob/master/README.md#want-to-be-a-mentor). 2: Wait until mentees to contact you.
> 
> Note: As we are still in Alpha, more convenient options will be added soon to let you pair with your favorite mentor.

### Suggested actions to solve this issue
- [ ] Adding a new section to the homepage
- [ ] Explanation in simple words, for both target groups, how they can take action, with appropriate linking to relevant guides/pages.
- [ ] Creating an appropriate image for that section.

**Comment by crysfel** [comment]
@emmawedekind can you work on a design for this? I think we should include some instructions in the homepage about how to become a mentor/mentee

**Comment by rachelfranklin1** [comment]
would love to take this issue when the designs are ready!

**Comment by tureey** [comment]
For me it's okay @rachelfranklin1

**Comment by emmawedekind** [comment]
Hi! I'll check this out tonight :) Thank you!!

**Comment by Ruffeng** [comment]
Hi! How is the status of this issue? Is there something I can try to help here to make it possible for @rachelfranklin1  or @emmawedekind  ?

**Comment by michaeljamie** [comment]
Seconding what @Ruffeng said.  I'm also happy to help if needed, or if any additional pages are needing to be added to the coding coach website @rachelfranklin1 and @emmawedekind 👍
