### ISSUE TITLE
Ability to leave feedback for the interactions with mentor

### ISSUE THREAD

**Issue by iyashsoni** [Coding-Coach/coding-coach#319]
**Is your feature request related to a problem? Please describe.**
Yes. In current state, one cannot leave any feedback for the interactions one just had with a mentor. I believe a general feedback would be really helpful to others who comes to CC, seeking a mentor.

**Describe the solution you'd like**
A space where mentees can leave feedback on how they found the interactions with the mentor. Out of all the solutions, we could show up some tags on the mentors profile like "good conversationalist" "subject expert" "patient and calm" etc. So that it becomes better for the new mentee to choose a mentor. There's no need to show the descriptive feedback. 

**Describe alternatives you've considered**
I did notice there's a heart icon next to mentor's profile, but I believe it doesn't work as of now - meaning it's not accounted for anything. Even that can work as an alternative solution, but it's definitely not better than the solution I mentioned in point 2. 

**Additional context**
-

**Comment by emmawedekind** [comment]
:O I had no idea oops! Thanks @moshfeu !

**Comment by moshfeu** [comment]
No problem :) It's not feature.

![Screen Shot 2019-04-08 at 15 53 36](https://user-images.githubusercontent.com/3723951/55725514-91003100-5a16-11e9-9b0f-07d190a667e1.png)
