### ISSUE TITLE
Mentors.codingcoach.io home href and icon do not direct to main homepage

### ISSUE THREAD

**Issue by Dmeowmixer** [Coding-Coach/coding-coach#320]
"Home" href at https://mentors.codingcoach.io/ navbar redirects to https://mentors.codingcoach.io/ instead of the main codingcoach.io page.  
The same is seen with the Coding Coach Alpha icon in the Sidebar (Top Left).

If this was unintentional and should redirect to the main codingcoach site, can I this be assigned to me? It would be my first open source contribution!

**Comment by emmawedekind** [comment]
Actually... I think we can get rid of the links on both of those. We can remove the Home link from the nav, as there will never be a case where we'll need it. The About nav item links back to codingcoach.io. So feel free to remove both of these links!

**Comment by Dmeowmixer** [comment]
Just made the pull request, let me know if there were any issues.
