### ISSUE TITLE
Navigation to 'About', 'Mission' and 'Contact' only works from the home page

### ISSUE THREAD

**Issue by Cazaimi** [Coding-Coach/coding-coach#323]
# Issue

Navigation to the mentioned pages/headings does not work if the user is on the mock openings page.

## Description

The user should ideally be able to navigate to any of the headings in the `Navbar`. However, this is not the case as on clicking on any of the headings from the 'Mock openings' page, the user is not navigated to the heading clicked.

## Screenshot

![codingcoach](https://user-images.githubusercontent.com/13660453/57639572-d2fc3400-75cd-11e9-8560-f142b8bd477c.gif)

## Steps to Reproduce

- Navigate to Mock openings
- Click on one of `About`, `Contact` or `Mission`. 

## Direct Requirements

- On clicking the headings, the user should be navigated to the correct page.

**Comment by brentmclark** [comment]
I can grab this one.if it's not already in flight
