### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#33]
**Acceptance Criteria:**
- A user can sign up for a new account using their email address.
- A user can sign up for a new account using their social media accounts (oAuth).

![image](https://user-images.githubusercontent.com/7671983/48345346-1c4be500-e678-11e8-968d-377671762a91.png)

![image](https://user-images.githubusercontent.com/7671983/48345368-24a42000-e678-11e8-8403-9cc0a1b840f0.png)

Assets: https://projects.invisionapp.com/d/main#/projects/boards/6261486
Screens: https://projects.invisionapp.com/d/main#/projects/prototypes/15543566

**Comment by crysfel** [comment]
Done! Please wait until the PR for the textfield and button are merged. Also, we need a tab component before working on this task.

**Comment by emmawedekind** [comment]
The styles on this will be changing.

**Comment by emmawedekind** [comment]
Unfortunately @pandaa880 this is an Epic and cannot be assigned. If you'd like a specific task, please see the issues listed underneath this :)
