### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#34]
**Acceptance Criteria:**

A user can update the following required fields:
- Name
- Email address
- Job title
- Languages the user speaks

A user can update the following optional fields:
- Social media accounts
- Company
- Skills to mentor in (depends on account type)
- Skills to be mentored in depends on account type)

Users will be able to set their account type to be mentor, mentee, or both.

A mentor can update the following fields:
- Skills they are able to mentor in
- Proficiency of skills they are able to mentor in

A mentee can update the following fields:
- Skills they are looking to improve

All users are able to set themselves as a mentor.

**Comment by tureey** [comment]
Once the designs are ready. I'd love to take this one! 😄
