### ISSUE TITLE
Search For Mentor

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#35]
**Acceptance Criteria:**
- Users can search for a mentor using filters

Filters include:
- Languages spoken
- Geographic location (country, timezone, city)
- Topic to be mentored in (JavaScript, HTML)
- Topic short hands will be converted into their counterpart (JS => JavaScript, node => node.js)
- Gender

**Comment by shayanypn** [comment]
I'll take this one.

**Comment by moshfeu** [comment]
@emmawedekind is this issue ready for work? (designs, specs)

**Comment by emmawedekind** [comment]
I need to re-visit the designs. I'd love to assign you as soon as it's ready! Let me re-visit all of the designs tonight and I'll let you know as soon as they're ready! @shayanypn
