### ISSUE TITLE
Add a sitemap

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#350]
We need to add a site map to improve our SEO, `gatsby-plugin-sitemap` seems to be a good alternative

**Comment by MetalDent** [comment]
Hi, anyone working on this?

**Comment by crysfel** [comment]
@MetalDent nope, would you like to take it?

**Comment by MetalDent** [comment]
@crysfel yeah sure. Can you tell me how can I proceed?

**Comment by crysfel** [comment]
@MetalDent all yours! 

Just follow the steps in the documentation: https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/

Remember we are using yarn instead of npm.

**Comment by MetalDent** [comment]
@crysfel okay, so do we need to exclude any pages from the website or the default option will work?

**Comment by crysfel** [comment]
I don't think so, the default options should be good to go.
