### ISSUE TITLE
Blog page not rendering.

### ISSUE THREAD

**Issue by levivm** [Coding-Coach/coding-coach#356]
Hi, 

Blog is not rendering properly. It just displays a blank page. 

Attached you can find the screenshot with the error. 

![Screenshot](https://i.imgur.com/Lr2AGbG.png)

**Comment by Asjas** [comment]
Hi @levivm. That is most likely a cached service worker that is causing the issue. The blog is working fine on my side.

Try clearing the cache or unregistering the current service worker and see if it renders the page correctly.

**Comment by levivm** [comment]
Yep, you right, it is a cache issue. 

I cleaned cache, didn't work but then viewed from incognito mode and worked.

**Comment by Asjas** [comment]
Okay, try uninstalling the previous service worker. That will cause the new service worker to install when you open the blog website

https://love2dev.com/blog/how-to-uninstall-a-service-worker/

**Comment by levivm** [comment]
working perfectly.

**Comment by crysfel** [comment]
Closing this issue, thanks Asjas for helping out!
