### ISSUE TITLE
No logo in twitter / SOA reference

### ISSUE THREAD

**Issue by janwilmans** [Coding-Coach/coding-coach#357]
![image](https://user-images.githubusercontent.com/5933444/65816960-203a1480-e202-11e9-89d8-add210d69314.png)

No logo is displayed / contained? in the meta info extracted from the link ?

**Comment by crysfel** [comment]
Thanks @janwilmans for reporting the issue and @kingingcole for the quick fix!

**Comment by janwilmans** [comment]
![image](https://user-images.githubusercontent.com/5933444/66167879-c4c1b980-e63b-11e9-863b-17f1de94164c.png)

Not sure what got fixed, but posting on twitter is still quite blend....

**Comment by janwilmans** [comment]
Btw, I would to know how/why this works/doesn't work. I have the same problem on nullptr.nl and was not able to find out how to fix it yet.
