### ISSUE TITLE
Add a feature to link to a specific mentor

### ISSUE THREAD

**Issue by janwilmans** [Coding-Coach/coding-coach#359]
Linking to 
https://mentors.codingcoach.io/?name=janwilmans used to work, but now: 

https://mentors.codingcoach.io/?name=Jan+Wilmans

just brings me back to https://mentors.codingcoach.io

Can we have a feature to link to a specific mentor page?

**Comment by jaydm** [comment]
I am not able to replicate your issue.

The second URL you listed (https://mentors.codingcoach.io/?name=Jan+Wilmans) worked for me.

**Comment by mnttnm** [comment]
Same for me. I am not able to reproduce this issue. @janwilmans can you check again?

**Comment by janwilmans** [comment]
Correct, it was working again pretty much the same evening, not sure what changed, however its no-longer re-produce-able, so I closed this issue.
