### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#37]
**Acceptance Criteria:**
- Mentors and mentees can see whether they have any mentorship messages.
- Users can see their notifications at a glance.
- Users can clear all notifications.
- Users can clear individual notifications.

## Mentor
![image](https://user-images.githubusercontent.com/7671983/49695057-3acccf80-fb95-11e8-96b0-53815ea2df88.png)

![image](https://user-images.githubusercontent.com/7671983/49695049-212b8800-fb95-11e8-84b3-34ca6b2c7318.png)

![image](https://user-images.githubusercontent.com/7671983/49695053-25f03c00-fb95-11e8-8a37-cdcc6bdd2c1f.png)

## Mentee
![image](https://user-images.githubusercontent.com/7671983/49695059-44563780-fb95-11e8-9593-f131bfba74bd.png)

![image](https://user-images.githubusercontent.com/7671983/49695060-48825500-fb95-11e8-99a8-33bd5b97f561.png)

![image](https://user-images.githubusercontent.com/7671983/49695062-4cae7280-fb95-11e8-9152-42495efb0432.png)

# Assets
All icons, designs, and color hex codes can be found on the Sketch cloud here: _To be added_

**Comment by Cazaimi** [comment]
Hi @emmawedekind, could I take this up?
