### ISSUE TITLE
Request for joining the organization

### ISSUE THREAD

**Issue by akshitagupta15june** [Coding-Coach/coding-coach#387]
i want to contribute in coding coach.
Thankyou in advance.

**Comment by crysfel** [comment]
Hi @akshitagupta15june! Sorry for the late response 😅

We now have 2 week sprints where we commit to a few tickets and try to complete the work within the time span, you should join us in slack, there are a couple of channels you can join: #cc-product, #cc-product-client and #cc-product-api

See you around!
