### ISSUE TITLE
Turn Mentorship Guidelines into web page

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/coding-coach#391]
Currently, the "mentorship guidelines" is a [Google Doc](https://docs.google.com/document/d/1zKCxmIh0Sd4aWLiQncICOGm6uf38S0kJ0xb0qErNFVA/edit).

The task is to turn it into a webpage (similar to https://codingcoach.io/legal/cookies [[source code](https://github.com/Coding-Coach/coding-coach/blob/master/content/legal/cookies.md)]) for better SEO and performance.

**Comment by TommiKorhonen** [comment]
You guys still need help with this? I am interested, but need more info etc.

**Comment by moshfeu** [comment]
Hi, thank you!
I've updated the description. Let me know if it clear.
