### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#43]
**Acceptance Criteria:**
- Users will be able to view their profiles.

Profile data will include:
- A badge indicating whether a user is mentor, mentee, or both.
- Name
- Job title (optional)
- Geographic location (City, country, timezone)
- Languages spoken
- Skills to be mentored on (mentee profile only)
- Skills to mentor in (mentor profile only)
- Recommendations (mentor profile only)

**Comment by linux-nerd** [comment]
I will be working on this, once the design is final.
