### ISSUE TITLE
Registration Welcome Email

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#45]
**Acceptance Criteria:**
- Users will receive a welcome email upon registration asking them to confirm their account.
- Text [TBD]

**Comment by jagzviruz** [comment]
Any recommendations on how to send emails? 
- Do we integrate with a email provider like mail chimp/sendgrid that provides templates ?
- Do we build a FE backend that uses something like `nodemailer` to send emails?

**Comment by jagzviruz** [comment]
[Amazon SES](https://aws.amazon.com/ses/pricing/) seems to be the cheapest of all alternatives with the highest free usage tier.

**Comment by crysfel** [comment]
@jagzviruz This tasks is only about creating the template for the email, the backend team will be responsible to actually sending the email.
