### ISSUE TITLE
Mission Statement

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#47]
**Acceptance Criteria:**
- Mission statement is easy to find.
- Document is in progress.

**Comment by tureey** [comment]
Does this epic include something else than the section on the home? The same for **About** and **Contact**.

If the answer is `YES` it's okay, if not, we could close them and clean up the backlog slowly!
@emmawedekind @crysfel

**Comment by tureey** [comment]
I've seen that the first issues were created as epic. I think #47 #48 #49 are meant to de development that's already done. by let's wait for @emmawedekind . I'll have to read docs about how exactly issue-task is realted in github to do a good proposal on how we can organize things.

**Comment by emmawedekind** [comment]
I believe these epics are ready to close, so long as all of those are merged to develop. Are all of the sub-tasks/issues/etc. merged?

**Comment by tureey** [comment]
At least related to Mission #56 and About #55  yes. There were one task for each other. Both developed, closed and merged @emmawedekind
