### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#49]
**Acceptance Criteria:**
- Contact Us is available on the site footer or navigation.

**Comment by gibsonhan** [comment]
I would like to claim this issue

**Comment by Ragzzy-R** [comment]
Hi can anyone please assign this to me?

**Comment by emmawedekind** [comment]
You were not added to the Coding-Coach team. Please in the future request access.  I have added you but it seems to be taking a while to update.

**Comment by Ragzzy-R** [comment]
seems like someone else is already working on it and its 80% done. So i just added some style fixes and created a merge request #93
