### ISSUE TITLE
Sign up with email

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#52]
As a user I want to sign up into the app using my email address. Name, Email, Password and a checkbox to accept the terms and conditions.

Once I have entered my data, I want to click the `Sign Up` button to create my account. After the server successfully create my account, I should be redirected to the main page (TBD, maybe profile page? Or search?).

When implementing this, make sure to create a `components/Textfield` component, we want this component to be reusable in other parts of the application.

```
const classes = {
  root: styles.someCustomClassForTheRootElement,
  input: styles.customCssForTheInput,
  label: 'something-here',
};

<Textfield value={value} onChange={onChange} classes={classes} label="Email" />
```

Same for the Checkbox, we want reusable components.

**The scope of this class is only to define the UI in the clientside**. For the actual login in the backend take a look at:

https://github.com/Coding-Coach/coding-coach-api/issues/9
https://github.com/Coding-Coach/coding-coach-api/issues/12

![image](https://user-images.githubusercontent.com/7671983/48345332-11915000-e678-11e8-986c-73fe531c6ea9.png)

**Comment by jagzviruz** [comment]
Using social login will eliminate the need for email validation and the need to securely store passwords.

**Comment by crysfel** [comment]
@jagzviruz there's another task for that coming up ;) but we are allowing users to use their email to signup as well.

**Comment by gibsonhan** [comment]
Is anyone working on this?

**Comment by crysfel** [comment]
We don't have the design for this or wireframes, I don't want to waste your time on something that we might ended up removing xD

**Comment by gibsonhan** [comment]
Hey @dhrubesh, I inquired about this issue first. I am not sure if you ignoring my comment above...

**Comment by emmawedekind** [comment]
I will assign this to both of you @gibsonhan and @dhrubesh . Please coordinate together.

**Comment by gibsonhan** [comment]
🔨🔪🔨I DEMAND ISSUE ASSIGNMENT BY COMBAT 🔨 🔪🔨. jokes aside. Will do when designs are out.

**Comment by Ragzzy-R** [comment]
This should be official code of conduct when requesting to assign task. 😂🤣

**Comment by emmawedekind** [comment]
I agree. Let me talk with @crysfel . Ultimately I'd love for people to work together but I also understand this is difficult based on locations.

**Comment by emmawedekind** [comment]
But also... we're not ready to begin this task yet as the designs are in-progress.

**Comment by dhrubesh** [comment]
@gibsonhan Let's work together if that's cool with you?

**Comment by dhrubesh** [comment]
@gibsonhan Let's work together if it's fine with you?

**Comment by FacundoGFlores** [comment]
Is there any requirement for social login? Any service like Auth0 or Firebase are going to be used?

**Comment by crysfel** [comment]
Just to be clear, this task is only to build the UI in the frontend, we still don't have the final design so please be patient.

**Comment by emmawedekind** [comment]
Yes, I am working on this, but the Privacy Policy, Cookies, and Terms & Conditions have higher priority.

**Comment by emmawedekind** [comment]
Sign Up is now finalized in terms of design. This issue only covers the email portion of the sign up.

**Comment by emmawedekind** [comment]
This issue is now ready for development. Note: This is only the mobile design; the desktop version will have different styling.  Additionally, this story only covers the email sign up.

**Comment by emmawedekind** [comment]
Hi, what's the status?

**Comment by swissarmykirpan** [comment]
I'm pulling this back into backlog because it needs refining

**Comment by emmawedekind** [comment]
What do you mean it needs refining...? We're not giving write access to anyone, sorry. That shouldn't stop you from developing.

**Comment by swissarmykirpan** [comment]
@emmawedekind @crysfel 
1. Since we have opted to use Auth0 - we no longer need to implement these pages in the front-end stack. Auth0 has the concept of hosted pages - https://auth0.com/docs/hosted-pages/login
2. The epic needs to be reorganised to consider that information
3. The epic needs to contain information about the entire Signup Flow, all the steps, such as:
    - Are we enabling social and email address/password login - and the rationale behind the choice (we could go completely passwordless either via email or MFA)
    - Are we doing any profile enhancement - https://auth0.com/blog/adding-fullcontact-to-your-auth-process-for-profile-enhancement/
    - What happens after sign up - do we present the user with additional profile information steps?
    - Mailing list sign up?

Each of these bits all fulfill the completion of Signup. It will allow us to create stories for each of the bits of work. At the moment this all looks haphazard. There are multiple issues open for the same thing, and it's incoherent and so it's very difficult for: 

1. A new person to come onboard and see what is what
2. For a stakeholder like @emmawedekind to understand what progress has been made
3. For the person who has identified what work needs to be done.

I apologise if this is overly critical, but we can do a lot better organising the work.

**Comment by emmawedekind** [comment]
I have given you write access @swissarmykirpan. You are now welcome to update the Epic with more detailed information: https://github.com/Coding-Coach/coding-coach/issues/33.

Please let me know if you have any questions, thanks!

**Comment by moshfeu** [comment]
@swissarmykirpan What about https://docs.google.com/document/d/1DbdRZBsyjbeBl9vddUyXCUWsgwdgyyUY2NIQitf3_Z0/edit?disco=uiAAAACIR2Yl4? (I know it's old but there is no conclusion there..)

**Comment by moshfeu** [comment]
Sounds good.
So it will be better to update the doc as well to avoid confusing.
(Or the doc is not relevant anymore?)

**Comment by HighWatersDev** [comment]
@swissarmykirpan @crysfel is there an issue for back-end implementation of Auth0? Will be happy to help there.
