### ISSUE TITLE
Main header

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#54]
As a visitor I want to see the main header in the landing page. At the top left it should include links to the three sections on the page.

- **About** When clicking on this link, the page should scroll to the about section
- **Mission** When clicking on this link, the page should scroll to the mission section
- **Contact** When clicking on this link, the page should scroll to the contact section

At the top right, there should be three links to the social networks accounts for the project.

- Twitter https://twitter.com/codingcoach_io
- Instagram TBD
- Facebook https://www.facebook.com/codingcoachio/

Follow design specs for the title, description, image, colors, etc. The *Learn More* button should take the user to the *About* section

**Comment by crysfel** [comment]
As a visitor I want to see the main header in the landing page. At the top left it should include links to the three sections on the page.

- **About** When clicking on this link, the page should scroll to the about section
- **Mission** When clicking on this link, the page should scroll to the mission section
- **Contact** When clicking on this link, the page should scroll to the contact section

At the top right, there should be three links to the social networks accounts for the project.

- Twitter https://twitter.com/codingcoach_io
- Instagram TBD
- Facebook https://www.facebook.com/codingcoachio/

Follow design specs for the title, description, image, colors, etc. The *Learn More* button should take the user to the *About* section

**Comment by tarang9211** [comment]
@crysfel Could you explain the difference between this and the landing page?

**Comment by crysfel** [comment]
@tarang9211 this is just the header of the landing page. The https://github.com/Coding-Coach/coding-coach/issues/59 is the epic, not really a task but a set of tasks. ZenHub creates issues for epics and actual tasks.

I'm going to assign this task to you.

**Comment by tarang9211** [comment]
Got it. Thanks.

**Comment by emmawedekind** [comment]
I created a follow-up story for the main header: https://github.com/Coding-Coach/coding-coach/issues/98

**Comment by crysfel** [comment]
This is done!
