### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#59]
As a visitor I want to see the landing page displaying details about the project.

This is an epic, please take a look at the tasks under this epic:

- Main header https://github.com/Coding-Coach/coding-coach/issues/54
- About section https://github.com/Coding-Coach/coding-coach/issues/55
- Mission section https://github.com/Coding-Coach/coding-coach/issues/56
- Contact section https://github.com/Coding-Coach/coding-coach/issues/57

![image.png](https://images.zenhubusercontent.com/5b9a800c3ca37c573e3792a9/4031fb9f-bd34-46ff-82bd-8cdf11fef7d8)

**Comment by pawansingh-snapwiz** [comment]
Where will be Login Button?

**Comment by crysfel** [comment]
@pawansingh-snapwiz no login button for now. We will add it later for sure ;)

**Comment by pandaa880** [comment]
If it is okay, I would like to work on this. What do i need to do ?

**Comment by linux-nerd** [comment]
> If it is okay, I would like to work on this. What do i need to do ?

@pandaa880 This is an epic. The tasks are linked on the top. You can check for open issue in the issues section.

**Comment by vittorioe** [comment]
Is still in dev? Would make it now.

**Comment by crysfel** [comment]
All task in this epic are completed! I will go ahead and close it!
