### ISSUE TITLE
Package.json homepage

### ISSUE THREAD

**Issue by palashmon** [Coding-Coach/coding-coach#68]
https://github.com/Coding-Coach/coding-coach/blob/0bad77aa8fd74608961ed9a90c1b19303775bd41/package.json#L5

This home page set in package.json is no loading and giving a 404 error. I think it should be [codingcoach.io](https://codingcoach.io/) instead. Please check this once.

Regards!

**Comment by edward-hong** [comment]
@palashmon thanks for pointing this out! I'll make a quick PR regarding this issue.

**Comment by emmawedekind** [comment]
I've approved. Merge in to develop once someone else approves.

**Comment by crysfel** [comment]
Closing issue as the PR has been merged!
