### ISSUE TITLE
Using i18n for image alt static text

### ISSUE THREAD

**Issue by arthurbuhl** [Coding-Coach/coding-coach#75]
## Issue Description
I think we should use `i18n` for this static text used for image alt.

## Code Link

https://github.com/Coding-Coach/coding-coach/blob/63eb963b2c12fa20ab2cb6519fb59aa2a4881b15/src/containers/App/App.js#L10

## Issue Level

Minor

## Issue Priority

Low

## Previous Discussion PR

https://github.com/Coding-Coach/coding-coach/pull/70#discussion_r219689084

**Comment by tureey** [comment]
Solved here https://github.com/Coding-Coach/coding-coach/pull/95

**Comment by emmawedekind** [comment]
I am going to close this as it's fixed with #95.

**Comment by emmawedekind** [comment]
I'll close this once #95 is merged.

**Comment by tureey** [comment]
Since **we have translated** the alternative texts should we **close this**? @emmawedekind
