### ISSUE TITLE
Travis badge in readme not working

### ISSUE THREAD

**Issue by palashmon** [Coding-Coach/coding-coach#76]
# Issue

## Description

Travis integration config has been added in PR #28 but it seems that repo has not been integrated with [Travis](https://travis-ci.org/) yet, as the Travis badge in readme page doesn't seem to be working.

## Steps to Reproduce

- [x] This [build](https://travis-ci.org/jagzviruz/coding-coach/builds/430392693) at `jagzviruz/coding-coach` seems to work fine.
  - [x] Image url - https://api.travis-ci.org/jagzviruz/coding-coach.svg?branch=feature/travis
  - [x] Badge working - ![](https://api.travis-ci.org/jagzviruz/coding-coach.svg?branch=feature/travis)

- [ ] But https://travis-ci.org/coding-coach/coding-coach does not exist yet.
  - [x] Image url - https://api.travis-ci.org/coding-coach/coding-coach.svg?branch=development
  - [ ] Badge not working - ![](https://api.travis-ci.org/coding-coach/coding-coach.svg?branch=development)

**Comment by nitish24p** [comment]
I think @emmawedekind will have to enable the build for the development branch on travis, and then itll work. :)

**Comment by emmawedekind** [comment]
I'll leave this for @crysfel :)

**Comment by crysfel** [comment]
Working on this!

**Comment by palashmon** [comment]
Any updates on this?

**Comment by emmawedekind** [comment]
@crysfel I'm oddly enough not getting ANY requests....
