### ISSUE TITLE
add AppVeyor (CI for Windows)

### ISSUE THREAD

**Issue by DanielRuf** [Coding-Coach/coding-coach#79]
## Description

AppVeyor is a CI service like Travis CI and others. But with one difference. We can test on Windows there. This would also catch issues like https://github.com/Coding-Coach/coding-coach/pull/78

## Direct Requirements

- [ ] automated CI on Windows

**Comment by timReynolds** [comment]
Travis CI [does have early stage windows support](https://docs.travis-ci.com/user/reference/windows/).

I assume the reasoning for wanting this is developer experience for this using windows to develop? Node and NPM on windows has gotten much better over the years but still isn't a nice experience, volume mounting the source into a docker container is another great alternative.

**Comment by DanielRuf** [comment]
I know and we should use Travis CI otherwise you have to provide and create your iwn solution. TravisCI uses Windows Server 2016 for the Windows builds and there are enough resources.
