### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by edward-hong** [Coding-Coach/coding-coach#91]
Currently http://coding-coach.github.io/ leads to desert 404 #68. Do we still need gh-pages?

**Comment by crysfel** [comment]
We are not using that domain anymore, instead we are using `codingcoach.io` that points to gh pages.

**Comment by emmawedekind** [comment]
It's a custom domain hosted through gh-pages. This is not an issue, it's the intended behavior. I'm closing this for now but if there is further conversation to be had, please re-open.
