### ISSUE TITLE
Migrate to JS-Lingui for i18n

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#97]
# Issue

## Description
JS-Lingui is a relative new library for internationalization, the API is very similar to React18next, in fact the author decided to do this in order to easily migrate from other libraries.

It supports plurals as well as custom formatting for texts. The most important thing is that this library comes with a CLI that we can use to manage the keys/text in all the different languages that we will support.

When it comes to manage the translations, it’s near impossible to find out which keys are unused/missing without an automated tool. JS-Lingui alleviates this pain, by providing a CLI that we can use in development.

Finally, this library adds a few KB to the final build which is great for performance!

## Direct Requirements

- [ ] Remove all i18next dependencies from `package.json`
- [ ] Remove the i18next code from  `src/config/i18n.js`
- [ ] Setup JS-Lingui https://lingui.js.org/tutorials/react.html
- [ ] Using the CLI add the two languages that we support (en, fr)
- [ ] Migrate the existing translations in the components that we have

## Indirect Requirements

- [ ] Install JS-Lingui
- [ ] Add JS-Lingui CLI to the dev dependencies
- [ ] Create a npm task in the `package.json` file to use the CLI https://lingui.js.org/tutorials/cli.html

**Comment by dhrubesh** [comment]
I'll be working on this.

**Comment by crysfel** [comment]
@dhrubesh sound good! Thanks!

**Comment by dhrubesh** [comment]
Hey @crysfel. I'm stuck in one thing.
So JS-Lingui creates a folder **locale/** (similar to **i18n/**) which resides outside of **src/** and which in turn is throwing this error (which is obvious): 
![image](https://user-images.githubusercontent.com/11453045/46312815-d2d19a00-c5e3-11e8-8863-0833a2ea25f5.png)
Can you suggest me a workaround with this one?
I couldn't find a way to create the **locale/** folder inside src.

**Comment by crysfel** [comment]
Use the `localeDir` configuration to set the path to `src/i18n`, then webpack should be able to load the files.

https://lingui.js.org/ref/conf.html#localedir

**Comment by crysfel** [comment]
PR has being merged, we are not using Lingui as our i18n library

**Comment by tricoder42** [comment]
> PR has being merged, we **are not** using Lingui as our i18n library

Just curious: are you or aren't you? :) It seems you **are** using Lingui in master, but if decided not to, may I ask what problem did you encounter?

Cheers

**Comment by crysfel** [comment]
@tricoder42 that was a typo that completely changed the meaning of my message 😅 

*We are **now** using Lingui*

I think Lingui is awesome!

**Comment by tricoder42** [comment]
Thank you, I'm glad you like it 👍
