### ISSUE TITLE
Main Header Follow-Up: Remove png background and use css only 

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#98]
# Issue
Relates to the Main Header Epic #54

## Description
The current landing page contains an extra div to set the background. While this works is not ideal, this task is about removing the following `div` from the landing page:

```
<div class="src-pages-home-home-mainHeaderBackground"></div>
```

Then we need to implement the background using css only, I've prepared an example on how to achieve this with only css: https://codepen.io/crysfel/pen/gdVyjW

Make sure to remove the `main-header-background.png` file from the assets folder.

**Comment by reeversedev** [comment]
I'll be interested in doing this.

**Comment by reeversedev** [comment]
I would be interested in doing this.

**Comment by crysfel** [comment]
@reeversedev I will create smaller tasks for this, so other people can take something

**Comment by AlexMunoz** [comment]
@emmawedekind can you review it :)
