### ISSUE TITLE
Main Header Follow-Up: Remove additional `<h1>`

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#99]
# Issue

## Description

In the home page, the current implementation uses two `h1`, we only need to have one `h1` in the entire page. 

The scope of this task limits to remove the second `h1` and put all the text in a single `h1` element, make sure to use the i18n library that we have.

**Comment by linux-nerd** [comment]
@crysfel I will be working on this

**Comment by tureey** [comment]
I did the refactor of a different things on my PR even before they decided to creat the `tech debt tasks`
Fixed here https://github.com/Coding-Coach/coding-coach/pull/73

**Comment by crysfel** [comment]
PR merged, thanks!
